### ISSUE TITLE
Improve field selection for sorting and display in Edit project settings

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#1]
Use a select box to choose the known fields, then for each selected one, show a text field to change the name. If the field is blank, use the current name

**Comment by jiho** [comment]
A UI could be

<img width="296" alt="screen shot 2018-11-02 at 00 42 53" src="https://user-images.githubusercontent.com/18445/47886061-47446680-de38-11e8-85e9-c8ecd7e73c22.png">

In that case, `area` is displayed as `Area [px]` and `mean` is displayed as `mean`.

Adding a field creates a new line in the table allowing to add yet another one.

**Comment by picheral** [comment]
Une discussion a eu lieu sur la pertinence de ce champ et sur une solution alternative à la sélection de ces champs pour chaque projet ce qui est fastidieux, et pas utilisé par les nouveau utilisateurs.

**Comment by grololo06** [comment]
On fait ou pas?

**Comment by jiho** [comment]
No Cf #461

**Comment by picheral** [comment]
NO, we do 461
