### ISSUE TITLE
Idée : sauvegarder jeux d'identification (multiprojets a date précise)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#102]
Permettre de visualiser un jeu de données tel qu'il était au jour d'une publication !

**Comment by picheral** [comment]
A remplacer par une doc qui indique qu'il suffit de télécharger TSV + Images => Proposer un bouton "EXPORT to BACKUP" qui créera une archive (TSV + vignettes) directement réimportable sans se soucier des options à cocher.

**Comment by picheral** [comment]
Re-vérifier que l'import "BackUp" actuel fonctionne correctement =>mise en place d'un test !

**Comment by grololo06** [comment]
C'est l'export DOI non? Donc on peut fermer cette issue?
