### ISSUE TITLE
Problèmes fréquents lors de la purge de projets

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#107]
Passer par `Erase objects with active filter or project` et sélectionner DELETEALL + delete project renvoie sur une URL du style `http://ecotaxa.obs-vlfr.fr/prjPurge/655?` qui mets très longtemps à charger et finit en général sur un page d'erreur nginx.

Le résultat est souvent que le projet apparaît ensuite vide d'objets mais qu'il faut refaire la même manip plusieurs fois pour finalement supprimer le projet.

**Comment by picheral** [comment]
Vérifier si pas réglé en v1.5

**Comment by picheral** [comment]
Problème moins fréquent depuis l'amélioration des performances de l'app. Il serait couteux de traiter en tache asynchrone (plusieurs heures). On propose un message d'avertissement indiquant qu'il faut patienter !
