### ISSUE TITLE
Manque des colonnes dans export .tsv de EcoPart

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#109]
Exemple: projet IADO 2017 (90).

Les données CTD sont correctement affichée dans les graphiques. L'affichage des données réduites des particules pour l'UVP montre des catégories 32-64 et 64-128 vides.

Dans l'export:

- il y a 79 titres de colonnes mais seulement 77 colonnes dans les données
- la catégorie 64-128 contient qq chose alors qu'elle devrait être vide.
- les données CTD sont décalées de 2 colonnes

Je suppose donc que cela est du au fait qu'il manque une colonne de classe de taille, au début (peut-être la plus petite) qui entraine un décalage de deux colonnes (manque une dans LPM [ui LPM biovolume) pour les données CTD.

C'est un bug assez sévère étant donné qu'il résulte en des données erronées, dont je ne me serai pas aperçu s'il n'y avait pas eu de CTD.

**Comment by picheral** [comment]
VERIFIER si pas resolu dans v 1.5

**Comment by picheral** [comment]
fixed 1.5
