### ISSUE TITLE
EcoPart: revoir nom de champs CTD

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#111]
Dans le fichier joint, les colonnes

- Time [yyyymmddhhmmssmmm]
- Oxygen [µmol/kg]
- Pot. Temperature [degC]

ont un titre qui correspond à ce qui est spécifié dans la page d'import, e.g. http://ecotaxa.obs-vlfr.fr/Task/Create/TaskPartZooscanImport?p=90 et pourtant elles ne sont pas associées à la bonne variable dans la base et sont mises dans `extrames01` à `03`.

[t_20170922_01.txt](https://github.com/oceanomics/ecotaxa_dev/files/1385868/t_20170922_01.txt)

**Comment by picheral** [comment]
Je pense que c'est réglé dans la v1.5 => VERIFIER !!!

**Comment by jiho** [comment]
Problème toujours présent aujourd'hui: EcoPart n'accepte pas les fichiers encodés en UTF8.

**Comment by jiho** [comment]
Pour simplifier, les en-têtes de colonnes devraient être ASCII pur

Passer de

```
"chloro fluo [mg chl/m3]": "chloro_fluo",
"conductivity [ms/cm]": "conductivity",
"cpar [%]": "cpar",
"depth [salt water, m]": "depth_salt_water",
"fcdom factory [ppb qse]": "fcdom_factory",
"in situ density anomaly [kg/m3]": "in_situ_density_anomaly",
"neutral density [kg/m3]": "neutral_density",
"nitrate [µmol/l]": "nitrate",
"oxygen [µmol/kg]": "oxygen_mass",
"oxygen [ml/l]": "oxygen_vol",
"par [µmol m-2 s-1]": "par",
"part backscattering coef 470 nm [m-1]": "part_backscattering_coef_470_nm",
"pot. temperature [degc] (any ref.)": "pot_temperature",
"potential density anomaly [kg/m3]": "potential_density_anomaly",
"potential temperature [degc]": "potential_temperature",
"practical salinity [psu]": "practical_salinity",
"practical salinity from conductivity": "practical_salinity__from_conductivity",
"pressure in water column [db]": "depth",
"qc flag": "qc_flag",
"sound speed c [m/s]": "sound_speed_c",
"spar [µmol m-2 s-1]": "spar",
"temperature [degc]": "temperature",
"time [yyyymmddhhmmssmmm]": "datetime"
```

à

```
"chloro fluo [mg chl m-3]": "chloro_fluo",
"conductivity [ms cm-1]": "conductivity",
"cpar [%]": "cpar",
"depth [m]": "depth",
"fcdom factory [ppb qse]": "fcdom_factory",
"in situ density anomaly [kg m-3]": "in_situ_density_anomaly",
"neutral density [kg m-3]": "neutral_density",
"nitrate [umol l-1]": "nitrate",
"oxygen [umol kg-1]": "oxygen_mass",
"oxygen [ml l-1]": "oxygen_vol",
"par [umol m-2 s-1]": "par",
"part backscattering coef 470 nm [m-1]": "part_backscattering_coef_470_nm",
"potential density anomaly [kg m-3]": "potential_density_anomaly",
"potential temperature [degc]": "potential_temperature",
"practical salinity [psu]": "practical_salinity",
"pressure [db]": "press",
"qc flag": "qc_flag",
"sound speed c [m s-1]": "sound_speed_c",
"spar [umol m-2 s-1]": "spar",
"temperature [degc]": "temperature",
"time [yyyymmddhhmmssmmm]": "datetime"
```

Changements:
![Screenshot 2019-03-28 at 23 00 25](https://user-images.githubusercontent.com/18445/55195601-5512d380-51ad-11e9-99ca-1b1e2d0de2ff.png)

À:
1. changer dans les fichiers CTD sur le serveur
2. répercuter dans la base (changement de nom de variables, suppression de colonnes cf #302 )
3. spécifier sur la page d'import
4. réimporter toutes les CTD

**Comment by jiho** [comment]
Tant qu'on y est, renommer `extrames01` etc. en `extra_01` etc.

**Comment by picheral** [comment]
On utilise l'automate fait par JO.

**Comment by picheral** [comment]
Import CTD et LPM OK.
Affichage nom CTD dans page import OK
Affichage CTD sur graphes OK
LPM = > **changer #/L en # l-1**

**Comment by picheral** [comment]
A faire : 
LPM = > changer #/L en # l-1 à la fois sur les graphes et dans les fichiers exportés pour être cohérent avec les unités BV.

**Comment by picheral** [comment]
Validé
