### ISSUE TITLE
renommer nbrobj et nbrobjcum dans table taxo

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#112]
Quand je regarde la table taxo j'ai deux colonnes nbrobj et nbrobjcum dont je suppose qu'elles sont mises à jour de temps en temps pour refléter le nombre d'objets assignés à une catégorie (nbrobj) ou à une catégorie et ses enfants (nbrobjcum) or:
- j'ai 118 catégories avec nbrobj > nbrobjcum
- j'ai 777 catégories avec nbrobj > 0 et seulement 511 avec nbrobjcum > 0
- quand je calcule l'équivalent de nbrobj (nb d'objets avec cet identifiant dans la table obj_head) maintenant, je trouve 850 catégories où nbrobj > 0 et des nombres très différents.

Ces champs sont-ils tenus à jour?

**Comment by jiho** [comment]
Il faudrait dans ce cas renommer le champ en `nbrobjbelow` pour être plus clair.

Idéalement, il faudrait renommer cela en `nb_obj` et `nb_obj_below` pour être plus anglophone et plus cohérent avec le reste.

**Comment by grololo06** [comment]
Included in #326
