### ISSUE TITLE
Warning quand aucune native feature n'est sélectionnée

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#117]
Il est maintenant possible de ne sélectionner que les deep learning features. Ce warning doit donc apparaitre seulement quand aucune feature n'est sélectionnée ET que Use deep learning features est décoché. Actuellement seule la première condition est vérifiée.

**Comment by picheral** [comment]
En STBY lié à la prédiction

**Comment by grololo06** [comment]
Je ne trouve pas ce warning dans le code, quelles sont les conditions pour le voir dans l'appli?

**Comment by jiho** [comment]
Cannot reproduce
