### ISSUE TITLE
Affichage lorsque navigateur à moins de 100%

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#124]
https://github.com/oceanomics/ecotaxa_dev/issues/new
![image](https://user-images.githubusercontent.com/18468240/33654293-f1fcc784-da6f-11e7-82f4-aeb04e527d4c.png)

**Comment by picheral** [comment]
Tester détection et indiquer warning (en rouge) conditionnel dans le TOPPER. Si pas de détection, le mettre dans le topper en haut à gauche flottant.
"Ecotaxa is optimized for 100% browser zoom display."

**Comment by jiho** [comment]
Je trouve ça inacceptable comme solution. On utilise Boostrap qui est justement destiné à gérer cela automatiquement. C'est simplement que bootstrap est mal utilisé pour l'instant.

**Comment by picheral** [comment]
Couteux à étudier et mettre en place pour plusieurs navigateurs => remettre le message qui est actuellement invalidé sur Niko ?

**Comment by jiho** [comment]
Je ne suis pas d'accord. Il ne faut pas le remettre. La solution actuelle ne marche pas: je la vois alors que mon navigateur est à 100% et du coup ça me pourrit toute les pages. Par ailleurs, je ne vois pas ce que ça apporte.

**Comment by picheral** [comment]
VALIDE. On n'affiche plus rien !
