### ISSUE TITLE
Application des TOOLS entre projet

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#128]
Les utilisatrices pensent que les spécifications des outils ne doivent pas être définies pour un utilisateur (et donc être les mêmes d'un projet à l'autre) mais plutôt être liées au projet pour cet utilisateur.
Si pas possible ou compliqué, ne pas enregistrer et mettre par défaut : 
IMAGE NAME
IMAGE NAME
ALL
FIT
100
disabled
disabled

**Comment by picheral** [comment]
Mettre une date de la derniere sauvegarde et purger les 50 plus anciens ?

**Comment by grololo06** [comment]
Closed, as a reduced  #398 issue is now present.
