### ISSUE TITLE
FILTRE ANNOTATEUR (contribute)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#131]
Doit présenter la liste des annotateurs et managers DU projet et non ceux de l'application.

**Comment by picheral** [comment]
Indiquer que la liste des annotateur est disponible dans la page "ABOUT".

**Comment by grololo06** [comment]
Je ne vois pas de quoi il s'agit. Une copie d'écran serait bienvenue.

**Comment by picheral** [comment]
![image](https://user-images.githubusercontent.com/18468240/94446510-06cb0000-01a9-11eb-98ab-ba2e269d0dee.png)

![image](https://user-images.githubusercontent.com/18468240/94446586-2104de00-01a9-11eb-8b7c-3c5b6fa0b2b8.png)

Il s'agit du filtre permettant de vérifier le travail de tri d'une personne en particulier.

**Comment by grololo06** [comment]
Le bouton "Advanced" présente la liste filtrée, qui a l'air correcte d'après mes tests (et le code). @picheral , je ferme l'issue?

**Comment by picheral** [comment]
Je te fais confiance. Une issue qui n'avait probablement été fermée suite à une MAJ.
