### ISSUE TITLE
Train & Predic V2 : utilisation autres projets

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#133]
ON doit pouvoir utiliser n'importe quel projet, même si on n'a aucun droit sur ce projet.

**Comment by picheral** [comment]
OK

**Comment by grololo06** [comment]
Est-ce que l'on parle de la page "AUTOMATIC CLASSIFICATION V2: Selection of Learning Set" ?

**Comment by picheral** [comment]
YES

**Comment by jiho** [comment]
Mais pas les projets "Privés"

**Comment by grololo06** [comment]
Pas de filtre sur les droit à ce jour, J'ai ouvert #490 pour ce qui reste.
