### ISSUE TITLE
Incohérence dans la structure des tables

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#140]
Actuellement, il y a 33640 samples, 26325 acquisitions et 22059 process, ce qui devrait être complètement impossible car il devrait y avoir au moins un process par acquisition et une acquisition par sample.

Cela vient probablement d'un reste du bug de départ qui considérait que des acquisitions ayant le même nom étaient identiques même si elles étaient dans des samples différents. Il faudrait:
- écrire une routine pour détecter ces cas là (objects avec `acquisid` identique mais `sampleid` différent), en faire une liste et les corriger un à un...
- *absolument* corriger cette incohérence dans la structure des bases par rapport à ce qui avait été spécifié initialement. Même si le lien continue d'être fait par le biais des objets (pour des raisons de performance) il faut absolument, à l'import, traiter cette structure hiérarchique des tables.

PS: Idéalement, il faudrait également que le lien soit possible entre les tables. J'ai récemment du chercher tous les samples appartenant à des projets zooscan. Le champ instrument est dans la table des `acquisitions` et, pour pouvoir refaire le lien avec les `samples`, j'ai du repasser par la table `objects`, ce qui a mis des plombes.

**Comment by picheral** [comment]
A retravailler lorsque structure base modifiée

**Comment by picheral** [comment]
cf #144

**Comment by grololo06** [comment]
Duplicate of #389.
