### ISSUE TITLE
Sort by name dans la liste des utilisateurs ne fonctionne pas

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#145]
Dans : Admin screen/Users

Lorsque nous cliquons sur la colonne "name" pour demander un tri alphabétique des noms d'utilisateurs, un changement se produit mais il ne suit aucun ordre alphabétique croissant ou décroissant. 
C'est la colonne email qui se met par ordre alphabétique.

**Comment by jiho** [comment]
Fermé par #193
