### ISSUE TITLE
Stale python processes are still present after cleaning tasks

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#149]
Clicking `Clean task data` on the task page removes the task from the list but leaves the python process `runtask.py #tasknumber#` running. It should kill it.

**Comment by grololo06** [comment]
I tried today on a long classification, indeed the python subprocess remains active.

**Comment by grololo06** [comment]
After code review, it would be unwise to kill the processes. They would leave stale files and others, worst case would be GPU handles. I haven't seen an orphan python process, which would be worse. The processes just die when they try to access their task, which was deleted in DB during the user action "Clean task".
