### ISSUE TITLE
Retain position in page after page reload

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#158]
When validated objects are not displayed, scroll down the page (because the classification of those objects is OK), select a few objects and change their name, save changes => the page reloads at the view is at the top. One then needs to scroll down again to find the place where one stopped looking for objects.

It would be better to retain where the browser was and scroll back down to it after reload. 

One could retain the scroll bar position (https://stackoverflow.com/questions/34261365/retain-scrollbar-position-even-after-reloading-using-javascript https://codepen.io/patrickkahl/pen/KFmAb http://www.sitepoint.com/forums/showthread.php?625439-Maintaining-Scroll-Box-Position-Upon-Page-Refresh) but this may be inaccurate because some objects were classified, hence removed.

A better way would be to retain the last object seen and find it again after page reload.

**Comment by picheral** [comment]
Mode de fonctionnement qui n'était pas anticipé.

**Comment by picheral** [comment]
VALIDE
