### ISSUE TITLE
Add shortcut for "Validate selection"

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#159]
<kbd>CTRL+V</kbd> would be natural but is taken by `Paste` which may be useful to paste stuff in a filter field; because this validation action changes the data, it should not be made by mistake.

<kbd>CTRL+L</kbd>? <kbd>L</kbd> quite far from <kbd>CTRL</kbd> but I cannot find anything better.
NB: <kbd>CTRL+L</kbd> is bound to "Open location" in many browsers but it probably not very used.

via Rainer.

**Comment by picheral** [comment]
CTRL L pour "validate selection"
CTRL N pour "Validate ALL...."

**Comment by jiho** [comment]
CTRL N est "Nouvelle fenêtre"

Il ne faut PAS de shortcut pour "Validate all". Nous avions mis comme principe qu'il fallait nécessairement regarder toute la page.

**Comment by picheral** [comment]
OUPS

**Comment by picheral** [comment]
VALIDE : 
- CTRL-L added
