### ISSUE TITLE
Remove "Update view and apply filters" button, at least for sorting tools

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#161]
By sorting tools I mean the row of tools at the top of the images region.

It is annoying to have to click it, the buttons are small.

For actual filters (left column) this is acceptable and the button could be big and at the bottom.

**Comment by picheral** [comment]
JO Préciser ???? Pas comprendre...

**Comment by jiho** [comment]
Il faut que toute action sur les boutons/menus en haut de la page (tools) entraine un changement immédiat de la page, sans avoir besoin de cliquer "Update view and apply filters"

**Comment by picheral** [comment]
VALIDE
