### ISSUE TITLE
Remove display fields that were added automatically

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#163]
- Sort by score => Score is displayed
- Add image name to display => Score and Image name are displayed
- Sort by major axis => Score, Image name, and Major axis are displayed

I would rather have only Image name and Major axis in the last one.

**Comment by picheral** [comment]
Quand on change le tri, on efface la colonne qui servait de tri des DISPLAY => plus d'accumulation !

**Comment by picheral** [comment]
VALIDE
