### ISSUE TITLE
Separate badges for counts in taxo view

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#164]
Currently it looks like
![screen shot 2018-05-16 at 18 37 41](https://user-images.githubusercontent.com/18445/40130855-84465712-5938-11e8-87d5-306b8f79c8d3.png)

It would be clearer and look better like:
![screen shot 2018-05-16 at 18 38 37](https://user-images.githubusercontent.com/18445/40130864-8dd11498-5938-11e8-9751-7d966fc89bf4.png)

(and there should be a count for "Unsure" ones too)

Alternatively, use one badge but grey and color the text.

**Comment by picheral** [comment]
VALIDE
