### ISSUE TITLE
Counts per taxon are often wrong

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#169]
The badges of counts per taxon often do not display the correct number, e.g.

Drag and drop removed predicted count, gives a wrong number and the badge is not the right color (see also #164 which could help with the badge issue)
![may-16-2018 18-54-38](https://user-images.githubusercontent.com/18445/40131581-a5425c52-593a-11e8-9946-d9dc7c41351a.gif)

Assigning by autocompletion does not update the numbers.
![may-16-2018 18-57-33](https://user-images.githubusercontent.com/18445/40131709-068a8cc8-593b-11e8-8b9a-a828917ce1a2.gif)

It should be accurate all the time.

Maybe a reset count button could stay somewhere to recompute them from the actual identification table, to fix potential bugs, but the current state is too buggy to be really useful.

**Comment by picheral** [comment]
VALIDE

**Comment by jiho** [comment]
Pas mis à jour quand on change en dubious/validé depuis le modal de l'objet.

**Comment by jiho** [comment]
Si/quand tout marchera, il faut supprimer les boutons minuscules [UC] et [HC] en haut qui sont difficile à atteindre/expliquer et ne garder que [Reset Counts ] (à renommer en [Recalc. counts]) et [Hide empty categories] en bas + les mettre en classe `btn`, peut-être `btn-primary` mais pas ce bleu qui est le même que pour predicted et sème donc la confusion.

**Comment by picheral** [comment]
A traiter en 1.6 en cours....

**Comment by picheral** [comment]
VALIDE
