### ISSUE TITLE
Define the ordering for the names of taxa in the autocompletion box

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#171]
Currently, the names look like
![screen shot 2018-05-17 at 14 29 13](https://user-images.githubusercontent.com/18445/40177394-cc5eb9ee-59de-11e8-94ee-5ec72efbc03a.png)
i.e.
1. first the names of taxa in the project (underlined)
2. then the names of taxa not in the project

The taxa in 2 seem ordered alphabetically:
![screen shot 2018-05-17 at 14 31 16](https://user-images.githubusercontent.com/18445/40177519-1fc6dcd8-59df-11e8-9320-9fe1628ce36b.png)

The taxa in 1 do not seem to have any particular order and this order seems to change from one day to the next. For operators using this dropdown routinely, it would be convenient to keep a definite (e.g. alphabetical) order so that they know to find `part (Annelida)` first, `part (Crustacea)` second etc.

**Comment by picheral** [comment]
La liste des taxons soulignés est celle des cinq dernières annotations...

**Comment by laurent-n** [comment]
La liste des taxon souligné est celle du preset. 
Les cinq dernières sélection ne sont affichés que si on ne saisis moins de 3 caractères
Actuellement le tri ne se faisait que sur la première partie du nom, sans tenir compte de la parenthèse, à présent c'est sur le nom affiché complet

**Comment by picheral** [comment]
VALIDE
