### ISSUE TITLE
Homogenise and simplify taxa names in the interface

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#172]
Taxa names are displayed as:
- `taxon (parent)`, which is constructed programmatically
- `taxon` only when the name contains a space because it is assumed to be a species and repeating the genus name does not make sense
- `taxon` only, in some parts of the interface where the disambiguation has been forgotten.

I propose to solve this problem in the taxonomy table directly, to (1) avoid having to compute names everywhere in the interface and (2) be more consistent.

Here is logic to solve the problem

```
let taxo be a table with columns: id, name, parent_id

set taxo.display_name = taxo.name

while any taxo.display_name is duplicated
   set duplicated taxo.display_name[i] to "taxo.name[i] (taxo.name[taxo.parent_id[i]])"
```

The display names will be recomputed over the whole taxo table whenever a new taxonomy is uploaded (or a new taxon is added). This is not to complicated to do and does not happen often. Then use `display_name` everywhere in the interface.

**Comment by picheral** [comment]
Laurent, Il faut lire l'intégralité de l'issue sur GitHub...

**Comment by picheral** [comment]
Liée à #257

**Comment by jiho** [comment]
Le choix de la syntaxe se porte sur `parent > enfant`.

Pour l'export, utiliser du texte simple = `parent > enfant`

Pour l'affichage, utiliser sur HTML avec
```
<span class="taxoparent">parent&nbsp;&#x276D;&nbsp;</span>enfant
```
(qui est un chevron vers la droite plus fin et plus discret)

**Comment by picheral** [comment]
">" dans la base sinon problème mais remplacement de caractère...
Le nouveau format sera acceptable à l'import comme le nouveau.
**Display name déjà implémenté dans le server taxo.**
Altidev fait un tour dans le code et évalue l'impact en terme de travail
On ajoute la double annotation sous les images ASAP.
Cette issue sera traitée après la mise en place du serveur taxo

**Comment by picheral** [comment]
Construction du display name: PAS EDITABLE dans le serveur taxo

1. Si espace, nom d'espèce : affiché seul
2. Si morpho: ajout parent
3. Si parent du morpho est un morpho, on ajoute grand parent
4. Si phylo, sans espace: on ajoute le parent

On implémente cette règle aujourd'hui et on voit ce que cela donne pour améliorer si nécessaire.

**Comment by jiho** [comment]
Tranfert de commentaire de Marc: 
Discussions internes... qui ont pris du temps :
Il faut garder le display name entier sous les vignettes. Passer à la ligne à chaque ">" systématiquement et mettre les parents et grands parents en caractères plus petits et pas en gras. Il faut en effet bien voir le nom final de la catégorie et utiliser et utiliser les parents comme détrompeurs.

**Comment by jiho** [comment]
Attendez un peu, je vais faire une nouvelle issue qui synthétise tout et clore celle-ci

**Comment by picheral** [comment]
Vérifié sur serveur de test
