### ISSUE TITLE
Delete project devrait être indépendant entre EcoTaxa et EcoPart

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#186]
Soit un projet `uvp part` côté EcoPart lié à un projet `uvp img` côté EcoTaxa.

Il devrait être possible de:
- supprimer `uvp part` sans affecter `uvp img` (cela semble OK)
- supprimer `uvp img` et retirer le lien côté `uvp part` (pour l'instant cela n'est pas possible car une table côté EcoPart a un lien vers vers la table projet côté EcoTaxa et empêche la suppression)

NB: vérifier comment cela est géré au niveau sample.

**Comment by picheral** [comment]
Le problème existe toujours. Il crée l'erreur suivante : 
![image](https://user-images.githubusercontent.com/18468240/48221533-ace1a700-e392-11e8-9d46-3eaf2a873fc7.png)

**Comment by picheral** [comment]
Il est d'ailleurs impossible de dissocier un projet Zoo et défaire le lien des samples PART avec ceux du projet ZOO. Pas de fonction pour cela même si on supprime le projet ZOO de la page metadata du projet.

**Comment by picheral** [comment]
Il faudrait aussi purger les histogrammes TAXO. Lorsqu'on fait les stats, on a encore la liste des taxon alors que nous n'avons plus de sample Ecotaxa associés. Cela se voir aussi dans la page d'edition des samples (ecoPart) dans laquelle il n'y a plus de sample associé mais encore des histo taxo.

**Comment by picheral** [comment]
VALIDE. Les histogrammes sont bien retirés du projet PART.
