### ISSUE TITLE
Changer l'outil "Merge project"

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#188]
Renommer en "Project > Merge projects"

Aboutit à une page avec un tableau des projets sur lequel l'utilisateur est project manager (cf #182  pour l'aspect de ce tableau).

Permet de sélectionner 1 ou n autres projets et permet d'optionnellement renommer le projet actuel (dans lequel les autres sont mergés).

À ce stade, il faut vérifier:
- que le mapping de tous les projets est compatible, avoir un warning explicite si ce n'est pas le cas et mettre NULL pour les colonnes qui n'existent pas dans certains projets
- que deep learning model est compatible et effacer les deep learning features si ce n'est pas le cas
- le lien avec ecopart (voir #184 ).
- cumuler les permissions des différents projets => un annotateur d'au moins un projet devient annotateur du projet final, pareil pour project manager et viewer.

Proposer l'option de ne pas supprimer les projets à merger.

**Comment by grololo06** [comment]
Issue un peu trop générale, qui référence une autre issue fermée. A ré-entrer spécifiquement pour chaque problème évoqué et restant après 2.4
