### ISSUE TITLE
Users: Création automatique des utilisateurs

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#189]
Le lien log in en haut à droite, renvoie vers une page avec
user, pass <kbd>Log in</kbd> (= changer le message Sign in en Log in)
Ajouter en dessous: Do not have an account? Please register.

Remplacer "To register, please send an email to one the following persons" par "in case of registration problem, contact one of the following persons"

Le register renvoie à un formulaire de demande d’enregistrement avec :
- Nom, Prénom (deux champs concaténés ensuite first  puis last name)
- Email (avec validation d’avoir une syntaxe correcte) et vérification des doublons. Quand l'email existe déjà:
    "Your email already exist, please contact one of the following persons"
- Mot de passe (répété deux fois, avec validation que les deux sont identiques)
- Raisons de vouloir un compte (facultatif)
- Un CAPTCHA efficace
- boutons <kbd>Cancel</kbd> (renvoie sur page de garde) et <kbd>Create me</kbd>: crée l'utilisateur sur l'instance.

Enlever la zone "Registration" dans la page de log in.

Créer un monitoring sur la table des users qui prévient d'application admin si elle augmente brusquement et bloque la création de nouveaux utilisateurs, pour éviter le SPAM -> Page API permettant de faire le monitoring de la table. Le faire surveiller par le monitoring de l'infrastructure.

#190

**Comment by picheral** [comment]
Ajouter le champ "Organisation". Présenter une liste déroulante des saisies précédentes. "Autre" vient en bas en dernier choix pour la saisie d'une nouvelle. Le but est d'inciter les utilisateurs à se référencer de façon homogène.
Ajouter le champ "Country". Facilite la levée d’ambiguïtés et permet de meilleures statistiques.

**Comment by picheral** [comment]
VALIDE
