### ISSUE TITLE
Users: Statuts et droits

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#190]
Après création, un utilisateur n'a aucun statut spécifique.

Les statuts sont ensuite:
1. Project creator: a le droit de créer un projet EcoTaxa ou EcoPart. Sur les pages listant les projets (http://ecotaxa.obs-vlfr.fr/prj/ et http://ecotaxa.obs-vlfr.fr/part/prj/), les personnes n'ayant pas ce statut voient le texte: "Please ask [email of user admin] for the permission to create a project", sujet "Permissions to create project in EcoTaxa/EcoPart", texte: "I need to create a project in EcoTaxa/EcoPart. Please grant me the `Project creator` status."
NB: faire tourner un script sur la table pour que tous les projects managers actuels aient ce statut là.
2. User admin.
3. Application admin

NB: Par projet (EcoTaxa) les utilisateurs peuvent avoir les permissions:
1. View
2. Annotate
3. Manage: la permission de manager le projet est indépendant du statut de project creator. NB: un project creator a les droits "Manage" sur les projets qu'il créé.

**Comment by picheral** [comment]
Renommer existant et s'en servir pour ZOO/PART

**Comment by picheral** [comment]
Obtention des droits de Project Creator:
Ces droits doivent être demandés au USER manager et non au APPLICATION manager.
Mettre un sujet par défaut dans l'email:
- Sujet : Please provide me the Project creation rights

**Comment by picheral** [comment]
VALIDE
