### ISSUE TITLE
SERVEUR de synchro TAXO et USERS (utilisateurs), principes

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#195]
Pour mémoire, nous avons décidé de l'unicité des Id de taxonomie entre les instances.

Le fonctionnement de la synchronisation TAXO et USERS (cf #194)  doit être choisi entre deux approches:

- La création de taxo ou utilisateurs se fait sur le serveur de synchro (impossible de créer un utilisateur ou une catégorie taxo sur une instance mobile ou si le serveur de synchro est HS). Le serveur détecte les instances connectées et envoie les données à intervalles régulier. Il peut aussi faire cette opération sur demande d'une instance locale pour permettre la MAJ d'une instance mobile par exemple.
- La création et la gestion se font au niveau local. Cela impose un système de synchronisation et la gestion des éventuels problèmes de doublons. 

Note :  des statuts particuliers doivent être gérés au niveau instance (Actif/Inactif...)

**Comment by jiho** [comment]
Closed by #230
