### ISSUE TITLE
MAJ Globale Aa Exp et Vol

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#197]
Nous sommes confrontés à la nécessité de faire des MAJ récurrentes de ces paramètres où à vérifier que les utilisateurs importent correctement leurs données en utilisant les bonnes valeurs. 
Un outil d’édition et de recalcul systématique à la disposition de l’application Manager… ou un tutoriel SQL éventuellement seraient très utiles.

**Comment by grololo06** [comment]
Toujours d'actualité?

**Comment by picheral** [comment]
Discussions en cours.... Je crois avoir vu une issue que je ne retrouve pas qui serait d'avoir une MAJ récurrentes de ces valeurs dans EcoTaxa à partir des valeurs de EcoPart. Vive l'unicité !!!!

**Comment by picheral** [comment]
La stratégie est pour le moment( en attente d'une refonte d'EcoPart) de mettre les projets à jour sur uvp_b et de ré-importer. Cette stratégie est valide pour tous les projets sauf ceux de GEOMAR !
