### ISSUE TITLE
Do not force to map fields for sorting and display in edit project settings

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#2]
Currently all fields have to be mapped even those whose name is unchanged, i.e.

```
kurt=kurtosis
area=area
```

The fields whose name is unchanged should not have to be mapped, i.e.

```
kurt=kurtosis
area
```

**Comment by picheral** [comment]
Voir issue #1 Improve field selection for sorting and display in Edit project settings
