### ISSUE TITLE
Documenter "Import images"

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#215]
A faire LOV

**Comment by picheral** [comment]
En relation avec le code derrière.

**Comment by grololo06** [comment]
Doc utilisateur ou doc en ligne?

**Comment by picheral** [comment]
Doc en ligne sur la page. 
Cette page IMPORT d'Ecotaxa doit être reconstruite en deux étapes : 
1) choix méthode parmi les 4 actuelles
2) page pour chaque méthode
