### ISSUE TITLE
Change settings loupe and info bubble

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#229]
Everyone keeps disabling them for every project so either:
- make them persistent per user, not per project
- disable them by default.

**Comment by picheral** [comment]
Déjà fait... mais à faire par défaut !!!

**Comment by picheral** [comment]
Ne fonctionne pas pour le SUBSET : le nouveau projet n'est ni conforme au projet source, ni disabled pour les deux

**Comment by picheral** [comment]
Réglage utilisateur par projet, sinon désactivé par défaut.

**Comment by picheral** [comment]
VALIDE
