### ISSUE TITLE
Taxonomie centralisée

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#230]
La table taxo est unique pour toutes les instances. Les identifiants numérique internes taxo sont donc les mêmes.

**La table taxo contient les champs: **
- id
- parent_id
- name
- type: phylo, morpho
- active: Y/N/D (on ne peut pas effacer un taxon étant donné que celui-ci peut être référencé qq part dans un table objets --identifications, historique etc.; par contre, pour les taxa qui ne doivent plus servir à de nouvelles identifications, il faut pouvoir les cacher). D: essaie de se DELETER sur toutes les instances.
- id_source: texte = identifiant dans la source taxo (e.g. UniEuk ID, Aphia ID si WoRMS, etc.)
- source_url: texte = url décrivant ce taxon dans la source (URL UniEuk, probablement construite à partir de l'UniEukID, URL Worms etc.
- source_desc: texte (1000 char)= texte de description de la source (e.g. reference taxo, notes de l'utilisateur, etc.)
- creator_email: email du créateur pour les créations par utilisateur (NB: on ne peut probablement pas stocker l'ID de l'user vu que cette table sera potentiellement indépendante des tables users sur les différentes instances). Sera vide pour les imports en bulk.
- creation_datetime: YYYY-MM-DD HH:MM:SS = date d'import pour les imports en bulk, date de création pour les créations manuelles
- id_instance: Référence de l'instance ECOTAXA d'où est issue la demande
- rename_too: premet de propager les modifications faites en central (MERGE, EDIT)

**Creation de nouveaux taxon:**
La création des nouveaux taxon se fait sur le serveur afin d'éviter tout problème de doublon. La création se fait VIA Ecotaxa et son serveur WEB. Sécurité assurée par l'IP du serveur TAXA.
Permission : tout (annotateur ou project manager ou project créateur) peut créer un taxon (à définir !!!!).
L'outil de création va permettre de chercher le parent dans la taxonomie (mêmes outils arbre/auto-complétion) et d'y créer le taxon. 
- Saisie du Nom
- Saisie du TYPE
Si catégorie "PHYLO", l'application vérifiera dans toute la base existante la présence de taxon du même nom ou de nom similaire pour afin de limiter la création de doublons ou pseudo doublons. 
Si "MORPHO", on ne cherche les doublons que chez le parent.
Si aucun doublon n'est trouvé, un formulaire permettra de renseigner les champs nécessaires pour la base taxo:
- Recherche du Parent
- id_source
- source_url
- source_desc. 
Les 3 champ source_id ne sont pas obligatoires pour permettre de créer de nouvelles espèces ou catégories "morpho".
L'email et la date de création sont automatiquement remplis.

Prévoir un mécanisme permettant au serveur de taxo de connaître l'utilisation des Id par chacune des instances (remonter l'info existant en local).
Il sera probablement nécessaire de gérer une liste d'utilisateurs et des permissions pour gérer la taxo centralisée.
Caractères latins pour les catégories, pas plus d'un espace, pas plus de deux mots.

**Règles:**
- majuscules obligatoire pour le premier caractère PHYLO et interdit sinon.
- trois caractères minimum
- autoriser les "-" et "+" (symbiose...)

**OUTILS de GESTION:**
- Passent au niveau central (MERGE, EDIT..)
- Les instances clientes fonctionnent en PULL. Ce sont elles qui demandent la taxo au serveur.

**REFLEXION:**
Ajouter des champs (tags) de classification associés plutôt que mettre les attributs directement dans l'arbre (genre, type, stade...)

**Comment by picheral** [comment]
Nouvelle Appli avec sa propre base des utilisateurs administrateurs
La création se fait depuis ecotaxa via un WS sur cet appli, sécurité assurée par l’IP du serveur ecotaxa
DB Ajouter une référence à l’instance créatrice id_instance
Prévoir un mécanisme de centralisation des stats
Première phase Type & Nom
Si phylo on cherche des doublons dans toute la base, pour Morpho on cherche juste sur le parent
Que des caractères latin + ‘-+‘ et apostrophe , pas plus d’un espace entre 2 mots, pas plus de 2 mots
Majuscule obligatoire pour le premier caractère de phylo interdit sinon
Longeur mini=3
Active Y/N/D d= à deleter pour ne pas le mettre sur les instances, quand ils ne seront plus présent nulle part (on le saura grâce au stat), on pourra les effacer.
Merge traité en central en ajoutant une colonne RenameTo
Écrans :
-	Login
-	Gestion users
-	Edit Taxo + merge
-	Import Taxo
-	Taxo error
-	Gestion des instances (clé secrète partagée) + date dernière connexion de chaque instance
-	Ecrans admin DB comme ecotaxa
-	Guide taxo
-	Browse Taxo & Guide (public) Table Nb au total sur les instances au moment où elles se sont connectées (statistiques utiles pour la gestion des catégories)
Web Services :
-	Teste un doublon de taxon
-	Crée un taxon
-	Envoi les modifications depuis une date GMT donnée
-	Collecte les statistiques par taxon

**Comment by picheral** [comment]
A relier #172

**Comment by jiho** [comment]
Le code de cette appli doit être indépendant et dans un nouveau repository (auquel il faudra transférer cette issue). Je l'ai préparé, il est là: https://github.com/oceanomics/ecotaxoserver

**Comment by picheral** [comment]
Active Y/N/D d= à deleter pour ne pas le mettre sur les instances, quand ils ne seront plus présent nulle part (on le saura grâce au stat), on pourra les effacer.

On ne pourra jamais savoir si pas active sur instance non connectée depuis longtemps ! =>
Active Y/N/D :

**Comment by picheral** [comment]
Accès par "No Results found" dans le Filtre taxo. Si nécessaire (car lien vers outils difficile), pointer vers le ACTION/Create new taxonomic catégory

Droit de création : 

- Annotateur d'un projet (au moins)
- Project creator
- Application manager

**Comment by picheral** [comment]
Un catalogue des instances sera créé, des stats (par instances/projet) maintenues afin de permettre de savoir si tout le monde est à jour et de prendre les bonnes décisions pour les catégories.
Pas d'outil d'exploration des instances. Seules les stats sont enregistrées..

Bouton ACTIVE devient STATUS avec trois états:

- ACTIVE
- NOT Reviewed
- To be DELETED (non sélectionnable dans PRESET, ni en autocomplétion)

On pourra purger une catégorie car toutes les instances seront scannées pour savoir quelles catégories pourraient être effacées.

D : sans "RenameTo" 

- On ajoute (DEPRECATED) au display_name
- Dans la classif manu (arbre à gauche), Ajout menu au dessus: "WARNING : this categroy is no longer valid. Please classify in another more suitable category" lien vers le commentaire de la catégorie qui décrit possiblement les actions à entreprendre (nouvelle catégorie de remplacement).

**Comment by picheral** [comment]
**Création de restriction sur les noms:**

- Aucune sur le serveur de TAXO
- Présente pour les éditeurs: caractères latins, +, -,", max un espace entre deux mots et un espace au total (à discuter) 

Règle des majuscules: premier Nom taxo. Interdite ailleurs.

Conserver Creation_date et Last_update. On affiche les deux.

Afficher le display_name dans la grille.

**Comment by picheral** [comment]
Id_source est réservé à l'importation en batch. 
On garde l'import actuel "mono_source".
On crée un outil import/export "complet" permettant de faire de l'édition de masse (pas d'intertion et que de la MAJ).

**Comment by picheral** [comment]
Discussions internes... qui ont pris du temps : 
Il faut garder le display name entier sous les vignettes. Passer à la ligne à chaque ">" systématiquement et mettre les parents et grands parents en caractères plus petits et pas en gras. Il faut en effet bien voir le nom final de la catégorie et utiliser et utiliser les parents comme détrompeurs.

**Comment by picheral** [comment]
.... cela nécessiterait de changer l'interface pour pouvoir proposer une liste de managers => changer le message pour indiquer que c'est le "top" manager car c'est actuellement un problème lorsqu'on est manageur de voir ce message : 
![image](https://user-images.githubusercontent.com/18468240/51784804-d965bd80-214e-11e9-9a4c-d6b646b7a36c.png)

**Comment by picheral** [comment]
La synchro se fait bien lorsqu'on arrive sur la page de création de taxon...

**Comment by picheral** [comment]
L'export XLS de la taxo crée un nom XLSX sans extension... Renommer avec une extension .xlsx

**Comment by picheral** [comment]
La MAJ du Type est testée et fonctionne sur une portion du TSV full exporté.

**Comment by laurent-n** [comment]
Les boutons Copy,CSV,XLS sont gérés directement par le composant datatables, je les ais mis car c'était simple, mais je pense qu'il posent plus de problèmes qu'autre chose (format lié à l'affichage et seulement ce qui est présent à l'écran) , je les supprime et ne laissé que copy, ça sera mieux.

Le full TSV export est celui qu'il faut utiliser et avec celui là ça marche correctement

Concernant les privilège, le privilège qui est implémenté est le droit de créer des projet, du coup en effet le message n'est pas raccord. 
Soit on étend aux projects manager (qui n'est pas un role global) soit il faut modifier le message et du coup lister les gens

**Comment by grololo06** [comment]
La fonction est dans le code. Merci d'ouvrir d'autres issue(s) en cas de souci.

**Comment by grololo06** [comment]
Pour les ajustements à venir, ouvrir une autre issue.
