### ISSUE TITLE
EXPORT: "Use internal ids to name image files" does not behave as expected

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#241]
Given the label, I would have expect the image files to be named `id.jpg`; in fact the internal id is prepended to the original image name.

Two solutions:

1. Change how it works
- Label: "Use internal ids to name image files (useful if several files with the same name were imported)"
- Name files `id.jpg`
- Put the same file name in `img_file_name` column of the exported `.tsv` files

2. Keep current behaviour but fix bugs
- Label: "Prepend internal ids to image files names (useful if several files with the same name were imported)"
- Name files `id_originalname.jpg`
- Put the same file name in `img_file_name` column of the exported `.tsv` files

PS: I would actually make 1 the default.

**Comment by picheral** [comment]
Remplacée par #257
