### ISSUE TITLE
Ajouter une licence pour les données téléchargées

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#244]
Il faudrait une licence pour les données téléchargées, pour être propre. Je vois, de la plus restrictive à la plus permissive:

- CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/ demande que les personnes utilisant les données citent leur source (Dataset collect by .... -- qu'il faut alors définir = liste des project managers) + le partage de modifications éventuelles des données sous la même license + interdit l'utilisation à des fins commerciales.

- CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/ pareil mais autorise l'utilisation commerciale

- CC BY 4.0 https://creativecommons.org/licenses/by/4.0/ pareil mais sans le share-alike

- CC0 https://creativecommons.org/publicdomain/ complètement public domain, aucune obligation d'aucune sorte.

J'aime bien CC BY-SA 4.0 par défaut, mais il faudrait probablement donner le choix entre les 4.

À rajouter dans "Edit project settings" + ajouter le texte de la license sélectionnée par le project manager au zip téléchargé.

**Comment by grololo06** [comment]
Comme ça va prendre des mois pour récupérer cette information pour tous les projets potentiellement exportables, il faudrait que ce champ soit rajouté ASAP.

**Comment by laurent-n** [comment]
Faudrait peut être aussi prévoir une licence privative / non CC

**Comment by grololo06** [comment]
@jiho , quand tu écris "ajouter le texte de la license sélectionnée par le project manager au zip téléchargé", ça veut dire dans les pages de téléchargement
Donc: - la page principale d'import
           - la page simple import ?

**Comment by jiho** [comment]
Non, ça veut dire ajouter un .txt dans le .zip téléchargé. Comme quand on télécharge du code source et qu'on a un fichier `LICENSE` avec le texte de la GPL par exemple.

Il faudra qu'on signale ailleurs dans l'UI quelle est la license pour chaque projet (page about project probablement).

**Comment by jiho** [comment]
> Faudrait peut être aussi prévoir une licence privative / non CC

Oui, il faut aussi une version C "all rights reserved"


![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Creative_commons_license_spectrum.svg/370px-Creative_commons_license_spectrum.svg.png)

**Comment by jiho** [comment]
Remplacé par #511 et #510.
