### ISSUE TITLE
EcoPart: Export des extra measurements CTD

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#247]
Réfléchir à la façon de pouvoir garder trace du nom du paramètre et de l'exporter avec les données.

**Comment by laurent-n** [comment]
Le mapping est bien conservé dans la base au niveau de chaque sample puisqu'il y a un fichier CTD par sample.
mais est assez peu utilisé, il ne sert que dans l'export raw

on peut voir un exemple des données ici
select pp.pprojid,pp.ptitle,psampleid,profileid,ctd_desc
from part_samples ps
join part_projects pp on ps.pprojid = pp.pprojid
where ctd_desc is not null;

![image](https://user-images.githubusercontent.com/11587919/93563870-09e41600-f989-11ea-950b-f348ff89a961.png)

**Comment by picheral** [comment]
Information disponible dans le Summary !!! Issue fermée.
