### ISSUE TITLE
Defaut affichage filtre TAXO (pb CRITIQUE)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#253]
Situation:
loggé
VIEW d'un projet sur lequel on n'a AUCUN droit (accès par la page SELECT OTHER PROJECTS)
![image](https://user-images.githubusercontent.com/18468240/46485611-4fd75c00-c7fc-11e8-8f93-0b6877279c7f.png)

**Comment by laurent-n** [comment]
il est marqué visible pour tous les visiteurs, on ne vois que les objets valide.

**Comment by picheral** [comment]
Bonjour,

regardez l'image sur GIT HUB. Vous avez des objets validés mais pas de taxonomie à gauche... On devrait au moins avoir la liste des catégories contenant au moins un objet validé.

Cordialement

Marc P.

**Comment by picheral** [comment]
Discussion avec LN. Impossible de reproduire ce jour !
