### ISSUE TITLE
Window "Go to classification screen" after using deep learning

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#259]
Normally after a prediction, a window inform us that it's done and ask us if we want to return on the classification screen or if we want to go to confusion matrix.
There is no window after running a deep learning.

**Comment by grololo06** [comment]
I can see a link.
![Capture d’écran de 2020-10-30 08-38-33](https://user-images.githubusercontent.com/20199778/97673026-5c861700-1a8b-11eb-945e-13d78e5576c6.png)
If the issue is still valid, thanks for re-opening it with more explanations (e.g. the menus to choose).
