### ISSUE TITLE
TOOLS : pouvoir trier par les metada (latitude, longitude, date, time)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#260]
Il est actuellement impossible de trier selon ces paramètres qu'il faudrait rajouter dans la liste comme nous avons rajouté la date de validation.

**Comment by laurent-n** [comment]
objtime déjà disponible
Ajouté  objdate, latitude, longitude

**Comment by picheral** [comment]
VALIDE
