### ISSUE TITLE
Revue de la page de création de compte

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#269]
Page http://.../logincreate voici ce qui devrait apparaître:

Create an EcoTaxa account

Ajouter un astérisque rouge pour les champs requis. E.g. First name*
Et en bas: * Required fields

Dans les champs, mettre en grisé des exemples/directives plutôt que répéter le nom de champ du dessus.
First name: John
Last name: Doe
Email: john.doe@foo.edu
Password: Type your password
Password confirmation: Retype your password

Warning: This server does not use encrypted communication (https) for performance reasons. This means that your password can be collected by a third party spying on the connection. Be careful which password you use here.

Organisation: Select from the list or type a new name
Le dropdown est énorme et ne se ferme pas quand on clique à l'extérieur. Il faudrait le réduire et le rendre moins envahissant.
Le select se colore en vert sans raison apparente.

Country: La fin de la liste de possibilités contient des trucs bizarres. Il faudrait probablement une possibilité "Other" à la fin.

Planned usage of EcoTaxa
NB: est-ce vraiment nécessaire? Qu'allons-nous en faire?

[ ] I agree with the following usage conditions:
- I will make a reasonable use of the resources of this system.
- I accept that my annotation activity and statistics are tracked and shared with the members of the projects I participate in and the EcoTaxa team, for the application to function.

In case of problem with this registration page, please email one the following persons so that they can create an account manually for you:
mailto avec sujet: EcoTaxa account creation (actuellement vide).

**Comment by picheral** [comment]
Cela ne coute "rien" de poser une question potentiellement inutile.... mais peut aussi nous donner une info qualitative sur la motivation des utilisateurs.

**Comment by jiho** [comment]
Ça coûte à l'utilisateur ;-)
Ne pas le mettre en obligatoire  et mettre "Planned usage of EcoTaxa (optional)" en titre?

**Comment by jiho** [comment]
Aussi, en anglais le nom de la page devrait plutôt être "createlogin" (que "logincreate") voire même plutôt "register".

**Comment by jiho** [comment]
Je vois register comme URL et "EcoTaxa: Create an account" comme titre ce qui est OK.

Sinon: User Creation Reason -> Planned usage of EcoTaxa

**Comment by jiho** [comment]
Ah et puis le champ Organisation se colore en vert, je ne sais pas pq. C'est bizarre en tt cas.

Et le champ Country est moins haut que les autres, pour une raison que j'ignore.

Enfin, la mise en page avec tableau n'est pas vraiment la façon dont Bootstrap est sensé être utilisé et cela se voit dans l'espacement vertical entre le champs, le fait que ce soit bloqué à gauche et pas dynamique quand on change la taille de la fenêtre du navigateur. EcoTaxa n'est pas fait pour être complètement accessible depuis un téléphone mais pour cette page, d'enregistrement, il serait utile (et facile) de l'être.

**Comment by picheral** [comment]
Validé.
