### ISSUE TITLE
Prediction : filtres selection projets

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#273]
point 4 suggestion Laetitia : 

J'ai voulu lancer une prédiction à partir de deux projets : l'un avec le mot "point B" dans le titre du projet et un autre avec le mot "modele". Lors du moment du choix du learning set, j'ai donc utilisé "Filter on title" où j'ai écrit "point B" : j'ai sélectionné mon premier projet. Je réutilise "Filter on title" où je tape "modele" : mon second projet souhaité apparait, je le sélectionne. En passant à l'étape suivante, je réalise que ma sélection du premier projet n'a plus été prise en compte dû à la deuxième recherche par filtre. Le seul moyen d'avoir ces deux learning set sélectionné est de ne pas utiliser les moteurs de recherches et de les chercher directement dans toute la liste.
-> on devrait pouvoir sélectionner plusieurs learning set même en utilisant les moteurs de recherches. Aussi il serait bien alors de pouvoir voir la liste de la learning set au fil de nos sélections afin de modifier si nécessaire.

**Comment by grololo06** [comment]
Bug (loss of user input data) and feature (recall selected project over the pages).

**Comment by grololo06** [comment]
Closed in favor of #518 and #517
