### ISSUE TITLE
Pb calcul histogramme de plancton (EcoPart, UVP5)

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#276]
Projet EcoPart: 
https://ecotaxa.obs-vlfr.fr/part/prj/121

Projet EcoTaxa correspondant
https://ecotaxa.obs-vlfr.fr/prj/1343

Je peux faire toutes les opérations mais le calcul du taxonomy histogram plante à chaque fois alors que le plancton est trié à 100%. Ni Marc ni moi ne voyons d'où vient le bug. Une métadonnée essentielle manquante?

Message d'erreur:
```
t_20180922_1 : Detailed & reduced Histogram computed
t_20180922_1 : reduced Histogram computed
t_20180922_1 : Matched
t_20180922_1 : Taxonomy Histogram can't be computed : unsupported operand type(s) for *: 'float' and 'NoneType' 
t_20180922_1 : CTD imported
```

**Comment by laurent-n** [comment]
C'est parce que la donnée sur la taille du pixel est manquante dans le sample.

**Comment by picheral** [comment]
Pb à régler dans Zooprocess
