### ISSUE TITLE
Selected taxon in the taxonomic filter is lost on save

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#278]
On the classif page, the selected taxon is highlighted in grey. When the page is saved (<kbd>CTRL+S</kbd>), the colouring disappears (although the selection stays).

**Comment by jiho** [comment]
Marc: Le coloriage des catégories ne fonctionne plus (se perd après le CTRL-S) sur Firefox 64.0.2.

**Comment by picheral** [comment]
... mais maintenant on passe à la catégorie cible ! On n'est plus dans cette qu'on triait !

**Comment by picheral** [comment]
le CTRL-L fait aussi perdre le coloriage en gris.

**Comment by picheral** [comment]
Validé
