### ISSUE TITLE
Autocomplete sometimes remembers the previous taxon instead of the last one

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#280]
Steps to reproduce:
- select objects
- type a name (e.g. Copepoda), autocomplete, apply
- save
- select (other) objects
- type another name (e.g. Detritus)
- save

Expected:
Detritus is in the autocomplete box

Result:
Copepoda is in the autocomplete box

**Comment by jiho** [comment]
Cannot reproduce it on Safari, logged as application admin.

**Comment by picheral** [comment]
Valide

**Comment by jiho** [comment]
Apparently still problematic (Cf #293). Needs to be reproduced.

**Comment by grololo06** [comment]
I suspect it will never happen again after recent optimizations on classification UI javascript so I close.
