### ISSUE TITLE
Classification page sometimes suddenly reloads

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#281]
On random occasions, the classification page suddenly reloads, loosing the current selection and classifications if they were not saved.

This happens ~ once a day on average.

**Comment by grololo06** [comment]
There are 3 steps in classification V2. Can you remember in which step was the reloading seen?

**Comment by jiho** [comment]
It's not in automatic classification, it is in the manual classif page.

**Comment by grololo06** [comment]
Ça date d'un changement précis: avant, les outils en haut de la page (tri, direction de tri, affichage d'infos etc.) nécessitaient de cliquer le bouton "Apply filters" ou un truc comme ça. On a demandé à ce que ce soit automatique (l'utilisateur clique le bouton de changement d'ordre de tri et pouf ça change). Depuis, ça reloade un peu quand ça veut en plus des moments où on le lui demande.

**Comment by grololo06** [comment]
![image](https://user-images.githubusercontent.com/20199778/80499972-e5ea4e80-896d-11ea-8430-a46b266f8bce.png)

**Comment by grololo06** [comment]
It is obviously a race condition, but on the most complex page of the application, so not easy. The problem reproduces frequently for a user after morning sequence which is:
- Login
- Go to project
But, if the project was loaded _before_ by someone else (me), then the problem does not appear, like this morning.
Note: User PC is very OK, 8go RAM, 64b, Core i5 gen 7

**Comment by grololo06** [comment]
To deploy in 2.2.7
