### ISSUE TITLE
Amélioration EXPORT (summary)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#287]
Ajouter les metadata "mandatory" (date, position...) du sample dans l'option summary.

Petite tache nécessaire pour NAGOYA... et donc si possible dès maintenant !

**Comment by laurent-n** [comment]
Fait, dispo sur test
    
    Le 25/01/2019 à 14:26, picheral a
      écrit :
    
    
      
      Ajouter les metadata "mandatory" (date, position...) du sample
        dans l'option summary.
      Petite tache nécessaire pour NAGOYA... et donc si possible dès
        maintenant !
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/oceanomics/ecotaxa_dev","title":"oceanomics/ecotaxa_dev","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/oceanomics/ecotaxa_dev"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Amélioration EXPORT (summary) (#287)"}],"action":{"name":"View Issue","url":"https://github.com/oceanomics/ecotaxa_dev/issues/287"}}}
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/oceanomics/ecotaxa_dev/issues/287",

"url": "https://github.com/oceanomics/ecotaxa_dev/issues/287",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by picheral** [comment]
Déplacer la colonne date juste après la position.

**Comment by picheral** [comment]
Valide
