### ISSUE TITLE
Ecotaxo server  : ajouter autocompletion dans la saisie du nouveau taxon

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#291]
Cela évitera des touché/coulé sur des noms qui existent déjà !

**Comment by picheral** [comment]
L'idée derrière cette demande est de pouvoir éviter la création d'un taxon de nom proche de celui d'un taxon existant.
Un autre besoin émerge de la création des premières catégories depuis l'implémentation. Il faudrait éviter la création de synonymes : coppepoda / copepoda... qui viendraient polluer la base et nous ajouter du boulot de correction.

**Comment by jiho** [comment]
https://github.com/oceanomics/ecotaxoserver/issues/6

https://github.com/oceanomics/ecotaxoserver/issues/7

and #372 for a better workflow.
