### ISSUE TITLE
Ajustements et bugs v 2.0, taxonomie

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#293]
Laetitia, Guillaume, Juliette et Corinne VEULENT avoir systématiquement un parent qui accompagnent le TAXON dans le filtre TAXO => changer la règle du display_name pour ajouter systématiquement un parent.

Quick PRESET : il faut pouvoir utiliser une table projet avec un filtre (le même que d'habitude) pour sélectionner directement un projet qu'on sait contenir la bonne liste de taxons.... en plus du filtre implémenter sur les taxons.

Dans l'autocompletion, il faut avoir TOUJOURS la possibilité d'accéder à l'outil de création du TAXON, sans avoir à taper un taxon qui n'existe pas.

**Sur Chrome 71.0.3578.98, divers problèmes** : 
Le TAXON doit être en gras dans les vignettes comme dans le filtre TAXO 
La page de création du taxon (accessible par le bouton CREATE TAXON) ne s'ouvre pas mais s'affiche tout en bas de la page taxo/browse... C'est par contre OK sur Firefox.
Outil preset ne s'affiche pas correctement dans la page.
Problèmes d'instabilité de la page affichée (page vignettes). je vous propose d'appeler Laetitia J. au 04 93 76 38 40 car c'est difficile à expliquer.

Sur Chrome comme sur Firefox, le problème de "mémoire" dans l'autocompletion qui persiste. Le dernier taxon affecté par un CTRL-S n'est pas toujours gardé en mémoire... C'est le précédent qui s'affiche. Issue que nous croyions résolue.

Problème d'affichage (avant validation) dans le cas où un taxon a trois parents (Podolampas)... ou nom trop long. Les vignettes se décalent vers la droite.
![image](https://user-images.githubusercontent.com/18468240/52058626-24753b80-2568-11e9-8716-a3f17ada153f.png)
devient : 
![image](https://user-images.githubusercontent.com/18468240/52058657-36ef7500-2568-11e9-9bdf-7d2e290d97db.png)

Vérifier aussi ce taxon Podolampas qui semble apparaître deux fois...
![image](https://user-images.githubusercontent.com/18468240/52059088-2986ba80-2569-11e9-828c-489adf2fbc50.png)

**Comment by grololo06** [comment]
Ca m'a l'air important, par contre comment je peux reproduire le comportement fautif?

**Comment by picheral** [comment]
Il faut qu'on se mette ensemble devant un écran. Tu pourrais demande rà Laetitia qui est à l'origine de l'issue.

**Comment by jiho** [comment]
Parent systématique: on a défini une règle ensemble qui détermine le comportement actuel

Quick preset: fait

New taxon dans autocompletion: #370 

Taxon en gras: works for me

Page create taxon dans chrome: works for me

Outil preset ne s'affiche pas correctement dans la page: works for me

Instabilité de la page affichée: #281 

Pb autocompletion qui retient le mauvais taxon: #280 

Pb de nom trop long: #371

Pb pour podolampas: https://github.com/oceanomics/ecotaxoserver/issues/5
