### ISSUE TITLE
Forçage saisie des chanmps URL et Description

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#294]
Serait il possible de forcer l'écriture sur le champ URL quand c'est du phylo qui est à créer

Serait il possible de forcer l'écriture sur le champ description quand c'est du morpho qui est à créer

Pour avoir une source justifiant la création et assitée le modérateur Taxo dans la validation

**Comment by jiho** [comment]
Amanda l'a mis dans les issues de ecotaxoserver: https://github.com/oceanomics/ecotaxoserver/issues/1
