### ISSUE TITLE
Profil UVP comme vignette

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#296]
Dans BOUM, une image est en fait un profil UVP

https://ecotaxa.obs-vlfr.fr/objectdetails/13727287?w=1473&h=1099

Cela semble plutôt un pb zooprocess voire un pb humain (copier coller erroné). Cependant il faudrait vérifier dans les données brutes que cela ne décale pas les mesures des images suivantes (e.g. mesures faites sur image 1 associées à l'image 2 parce que l'image 1 importée est en fait ce profil).

**Comment by grololo06** [comment]
Je ferme?
