### ISSUE TITLE
Ecopart divers petits détails

### ISSUE THREAD

**Issue by fabienlombard** [oceanomics/ecotaxa_dev#303]
incohérence de pixelsize entre ecotaxa (en mm) et ecopart (en mm2) 

export « complete » de ecotaxa particle n’est pas complet… il manque plein de parametres du zooplancton (il est plus souhaitable d’avoir le tsv complet) pour information dans tout les dossiers UVP j’utilise « à minima » les champs suivants
Bref, l’export complète est actuellement peu utile
Actuellement présent dans ecopart :
object_annotation_hierarchy   (attention noté “taxo_hirerarchy” dans ecopart)
minor
major

Actuellement absent dans ecopart :
object_area_exc
object_ferret
sample_id
sample_dn
sample_ship
sample_cruise
object_date
object_time
object_lat
object_lon
sample_bottomdepth
sample_ctdrosettefilename
sample_profileid

incohérence de pixelsize entre ecotaxa (en mm) et ecopart (en mm2)

**Comment by picheral** [comment]
Fabien
Ce n est pas dans le summary ?
Il faut prendre le pixel de EcoPart.
Marc

⁣Marc Picheral
Observatoire Océanologique 
181 chemin du Lazaret
06230 Villefranche sur mer
33 4 93 76 38 08
33 4 93 76 38 57
33 6 51 87 09 99​

Le 11 mars 2019 à 14:01, à 14:01, fabienlombard <notifications@github.com> a écrit:

**Comment by fabienlombard** [comment]
Si mais tout les pixelsize de ecotaxa sont en mm
Le summary est en mm2

Résultat on peut (et je me suis) trompé ... et comme aucune unité n’est 
indiquée c’est un bon piège à con dans lesquels je suis tombé

Comme par ailleurs toutes les données ne sont pas présentes dans 
écopart, ça encourage à utiliser les données d’ecotaxa et à prendre le 
mauvais pixelsize (ce que j’ai fait, ce que JO est en train de faire 
avec Thelma et Laure j’en suis presque certain)

Bref toutes mes routines d’export d’ecotaxa sont potentiellement 
biaisées

Fabien


Le 2019-03-11 19:08, picheral a écrit :

**Comment by picheral** [comment]
Pixel size traité dans issue #305 

Les metadata sont obtenues à partir du Summary exporté (au niveau SAMPLE et pas OBJET) en même temps que les données : sont-elles suffisantes ?

Les deux variables qui pourraient être exportées en plus sont 
- object_area_exc
- object_ferret

La problématique de la duplication de certaines metadata (pixel size) entre EcoPart et Ecotaxa est réelle et doit être traitée ! En attendant une meilleure gestion des application, nous pourrions ajouter un bouton dans EcoPart au même niveau que le "recompute histogramms" qui forcerait la MAJ des metadata dans Ecotaxa.

**Comment by jiho** [comment]
Les champs additionnels seront traités dans #312.

**Comment by jiho** [comment]
La synchronisation des metadata sera traitée dans #313
