### ISSUE TITLE
EcoPart: Units of ESD and biovolume

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#304]
ESD is marked as `[mm3]` when it should be `[mm]`.

biovolume is marked as `[ppm]` when it should be `[mm3]`.
biovolume could be `[mm3]/[L]` = `[part per million]` but currently it is not divided by the volume imaged => still in mm3

**Comment by jiho** [comment]
In the sample form, Pixel is marked in µm while it is mm.
e.g. 0.086 means the pixel is 0.086 mm wide (or tall)

**Comment by picheral** [comment]
On change aussi les µl.l-1 de la page d'accueil en **[mm3 l-1]**

**Comment by picheral** [comment]
Vérifier Zoo et LPM pour le calcul du BV qui doit partout être divisé par le volume.

**Comment by picheral** [comment]
Je ne teste pas ces calculs. JO ira dans le code pour vérifier.
Les unités sont par contre toujours indiquées en #/L dans la page générale (graphes et sélection des classes) même si OK dans les exports.

**Comment by jiho** [comment]
Il ne s'agit pas de vérifier des valeurs mais juste comment sont écrites les unités dans l'export et dans l'interface.

**Comment by jiho** [comment]
L'unité de pixel size est toujours fausse: mm pas µm

https://github.com/oceanomics/ecotaxa_dev/blob/f33dab7b10c4b04a408d8540a1526cb1865bfd64/appli/part/sampleedit.py#L49

**Comment by picheral** [comment]
NE RESTE QUE le dernier COMMENT de JO (nouveau) à faire !
