### ISSUE TITLE
EcoPart: for plankton histogram avgesd is not ESD and biovolume is incorrect

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#305]
`avgesd` is computed as `avarea*pixel*pixel`; this is the area but converted in mm2, it is not the esd. The esd would be `2*sqrt(area/pi)`.

The biovolume is computed as `n*4/3*pi*(avgesd/2)^3` except `avgesd` is not an ESD, so the result is incorrect.

In addition, the biovolume should be computed as the sum of the volume of each unitary particle, not n * the volume of the average particle. Demonstration:

```
> area <- c(10,20,500)
> pixel <- 0.086
> esd <- 2*sqrt(area*pixel^2/pi)
> esd
[1] 0.3068693 0.4339788 2.1698940
> sum(4/3*pi*(esd/2)^3)
[1] 5.407439
# correct
> 3*4/3*pi*(mean(esd)/2)^3
[1] 1.43472
# incorrect
```

**Comment by picheral** [comment]
Vérifier qu'il n'y a pas la même erreur dans le calcul des histogrammes de BV pour LPM.

**Comment by picheral** [comment]
Comment faire la MAJ des données ?
On utilise le même automate que pour le recalcul des CTD sauf si LN nous confirme qu'il a un outil pour cela.

**Comment by picheral** [comment]
J.O. ira vérifier dans le code.

**Comment by jiho** [comment]
Les nouvelles formules sont correctes.
