### ISSUE TITLE
Ecopart: date selection is exclusive while it should be inclusive

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#306]
Date between 2018-09-22 and 2018-09-22 does not return anything when there are profiles on this date. The bounds need to be specified as 2018-09-21 and 2018-09-23. I think it should use >= and <= rather than > and <.

**Comment by picheral** [comment]
A vérifier dans EcoTaxa aussi.
Pas si urgent mais si simple à régler (à priori)

**Comment by picheral** [comment]
Validé
