### ISSUE TITLE
Ecopart: figures de controle

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#307]
Enregistrer toutes les figures dans l'architecture EcoTaxa et pas dans le répertoire results du projet.

**Comment by picheral** [comment]
Il semble que ce soit OK pour les profils de particules mais pas pour le profil de la plongée.

**Comment by picheral** [comment]
Il semble que le Path soit OK : https://ecotaxa.obs-vlfr.fr/vault/pargraph0001/001869_depth.png
On ne s'explique pas la disparition des figures du répertoire !!!!
Ne peut être géré que par un ré-import... par le LOV ou par un process specifique par Altidev.

**Comment by picheral** [comment]
Généré à l'import.

**Comment by picheral** [comment]
On peut automatiser le ré-import des samples... LN vérifie de son coté.

**Comment by picheral** [comment]
Les figures de contrôle sont générées.
Vu le décalage temporel, nous utiliserons notre automate si nous souhaitons ré-importer massivement.
