### ISSUE TITLE
EcoPart : Modification de l'export RAW plancton

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#312]
Actuellement seules certains descripteurs sont exportés.
Il faut remplacer cela par un export de tous les descripteurs (champs mappés de la table objet). Retirer unités : utiliser les noms de champ de l'import
Ajouter psampleid pour permettre le lien avec le summary
corriger le nom de colonne taxo_hirerarchy en taxo_hierarchy
Utiliser le display_name et nom le name reconstruit

renommer "depth" en "depth_including_offset" 

NB : issue à traiter en dernier... et si possible dans ce milestone

**Comment by jiho** [comment]
Il y a actuellement 7 mapping différents pour les projets UVP utilisés respectivement
80  9  1  7  7  4  1
fois

[[1]]
n01=area  n02=mean  n03=stddev  n04=mode  n05=min  n06=max  n07=x  n08=y  n09=xm  n10=ym  n11=perim.  n12=bx  n13=by  n14=width  n15=height  n16=major  n17=minor  n18=angle  n19=circ.  n20=feret  n21=intden  n22=median  n23=skew  n24=kurt  n25=%area  n26=xstart  n27=ystart  n28=area_exc  n29=fractal  n30=skelarea  n31=slope  n32=histcum1  n33=histcum2  n34=histcum3  n35=xmg5  n36=ymg5  n37=nb1  n38=nb2  n39=nb3  n40=compentropy  n41=compmean  n42=compslope  n43=compm1  n44=compm2  n45=compm3  n46=symetrieh  n47=symetriev  n48=symetriehc  n49=symetrievc  n50=convperim  n51=convarea  n52=fcons  n53=thickr  n54=areai  n55=tag  n56=esd  n57=elongation  n58=range  n59=meanpos  n60=centroids  n61=cv  n62=sr  n63=perimareaexc  n64=feretareaexc  n65=perimferet  n66=perimmajor  n67=circex  n68=cdexc  n69=kurt_mean  n70=skew_mean  n71=convperim_perim  n72=convarea_area  n73=symetrieh_area  n74=symetriev_area  n75=nb1_area  n76=nb2_area  n77=nb3_area  n78=nb1_range  n79=nb2_range  n80=nb3_range  n81=median_mean  n82=median_mean_range  n83=skeleton_area

[[2]]
n01=area  n02=mean  n03=stddev  n04=mode  n05=min  n06=max  n07=x  n08=y  n09=xm  n10=ym  n11=perim.  n12=bx  n13=by  n14=width  n15=height  n16=major  n17=minor  n18=angle  n19=circ.  n20=feret  n21=intden  n22=median  n23=skew  n24=kurt  n25=%area  n26=xstart  n27=ystart  n28=area_exc  n29=fractal  n30=skelarea  n31=slope  n32=histcum1  n33=histcum2  n34=histcum3  n35=xmg5  n36=ymg5  n37=nb1  n38=nb2  n39=nb3  n40=compentropy  n41=compmean  n42=compslope  n43=compm1  n44=compm2  n45=compm3  n46=symetrieh  n47=symetriev  n48=symetriehc  n49=symetrievc  n50=convperim  n51=convarea  n52=fcons  n53=thickr  n54=areai  n55=tag  n56=esd  n57=elongation  n58=range  n59=meanpos  n60=centroids  n61=cv  n62=sr  n63=perimareaexc  n64=feretareaexc  n65=perimferet  n66=perimmajor  n67=circex  n68=cdexc  n69=kurt_mean  n70=skew_mean  n71=convperim_perim  n72=convarea_area  n73=symetrieh_area  n74=symetriev_area  n75=nb1_area  n76=nb2_area  n77=nb3_area  n78=nb1_range  n79=nb2_range  n80=nb3_range  n81=median_mean  n82=median_mean_range  n83=skeleton_area  n84=dl_score  n85=pi_score  n86=pi_percentage  n87=pi_counts  t01=dl_prediction

[[3]]
n01=area  n02=mean  n03=stddev  n04=mode  n05=min  n06=max  n07=x  n08=y  n09=xm  n10=ym  n11=perim.  n12=bx  n13=by  n14=width  n15=height  n16=major  n17=minor  n18=angle  n19=circ.  n20=feret  n21=intden  n22=median  n23=skew  n24=kurt  n25=%area  n26=xstart  n27=ystart  n28=area_exc  n29=fractal  n30=skelarea  n31=slope  n32=histcum1  n33=histcum2  n34=histcum3  n35=xmg5  n36=ymg5  n37=nb1  n38=nb2  n39=nb3  n40=compentropy  n41=compmean  n42=compslope  n43=compm1  n44=compm2  n45=compm3  n46=symetrieh  n47=symetriev  n48=symetriehc  n49=symetrievc  n50=convperim  n51=convarea  n52=fcons  n53=thickr  n54=areai  n55=tag  n56=esd  n57=elongation  n58=range  n59=meanpos  n60=centroids  n61=cv  n62=sr  n63=perimareaexc  n64=feretareaexc  n65=perimferet  n66=perimmajor  n67=circex  n68=cdexc  n69=score_dl  n70=kurt_mean  n71=skew_mean  n72=convperim_perim  n73=convarea_area  n74=symetrieh_area  n75=symetriev_area  n76=nb1_area  n77=nb2_area  n78=nb3_area  n79=nb1_range  n80=nb2_range  n81=nb3_range  n82=median_mean  n83=median_mean_range  n84=skeleton_area

[[4]]
n01=area  n02=mean  n03=stddev  n04=mode  n05=min  n06=max  n07=x  n08=y  n09=xm  n10=ym  n11=perim.  n12=bx  n13=by  n14=width  n15=height  n16=major  n17=minor  n18=angle  n19=circ.  n20=feret  n21=intden  n22=median  n23=skew  n24=kurt  n25=%area  n26=xstart  n27=ystart  n28=area_exc  n29=fractal  n30=skelarea  n31=slope  n32=histcum1  n33=histcum2  n34=histcum3  n35=xmg5  n36=ymg5  n37=nb1  n38=nb2  n39=nb3  n40=compentropy  n41=compmean  n42=compslope  n43=compm1  n44=compm2  n45=compm3  n46=symetrieh  n47=symetriev  n48=symetriehc  n49=symetrievc  n50=convperim  n51=convarea  n52=fcons  n53=thickr  n54=tag  n55=esd  n56=elongation  n57=range  n58=meanpos  n59=centroids  n60=cv  n61=sr  n62=perimareaexc  n63=feretareaexc  n64=perimferet  n65=perimmajor  n66=circex  n67=cdexc  n68=kurt_mean  n69=skew_mean  n70=convperim_perim  n71=convarea_area  n72=symetrieh_area  n73=symetriev_area  n74=nb1_area  n75=nb2_area  n76=nb3_area  n77=nb1_range  n78=nb2_range  n79=nb3_range  n80=median_mean  n81=median_mean_range  n82=skeleton_area

[[5]]
n01=area  n02=mean  n03=stddev  n04=mode  n05=min  n06=max  n07=x  n08=y  n09=xm  n10=ym  n11=perim.  n12=bx  n13=by  n14=width  n15=height  n16=major  n17=minor  n18=angle  n19=circ.  n20=feret  n21=intden  n22=median  n23=skew  n24=kurt  n25=%area  n26=xstart  n27=ystart  n28=area_exc  n29=fractal  n30=skelarea  n31=slope  n32=histcum1  n33=histcum2  n34=histcum3  n35=xmg5  n36=ymg5  n37=nb1  n38=nb2  n39=nb3  n40=compentropy  n41=compmean  n42=compslope  n43=compm1  n44=compm2  n45=compm3  n46=symetrieh  n47=symetriev  n48=symetriehc  n49=symetrievc  n50=convperim  n51=convarea  n52=fcons  n53=thickr  n54=tag  n55=esd  n56=elongation  n57=range  n58=meanpos  n59=centroids  n60=cv  n61=sr  n62=perimareaexc  n63=feretareaexc  n64=perimferet  n65=perimmajor  n66=circex  n67=cdexc  n68=kurt_mean  n69=skew_mean  n70=convperim_perim  n71=convarea_area  n72=symetrieh_area  n73=symetriev_area  n74=nb1_area  n75=nb2_area  n76=nb3_area  n77=nb1_range  n78=nb2_range  n79=nb3_range  n80=median_mean  n81=median_mean_range  n82=skeleton_area  n83=areai

[[6]]
n01=bx  n02=by  n03=width  n04=height  n05=area  n06=areai  n07=mean  n08=major  n09=minor  n10=feret  n11=area_exc  n12=thickr  n13=esd  n14=elongation  n15=range  n16=meanpos  n17=centroids  n18=cv  n19=sr  n20=perimareaexc  n21=feretareaexc  n22=perimferet  n23=perimmajor  n24=circex  n25=cdexc  n26=stddev  n27=mode  n28=min  n29=max  n30=x  n31=y  n32=xm  n33=ym  n34=perim.  n35=angle  n36=circ.  n37=intden  n38=median  n39=skew  n40=kurt  n41=%area  n42=xstart  n43=ystart  n44=fractal  n45=skelarea  n46=slope  n47=histcum1  n48=histcum2  n49=histcum3  n50=xmg5  n51=ymg5  n52=nb1  n53=nb2  n54=nb3  n55=compentropy  n56=compmean  n57=compslope  n58=compm1  n59=compm2  n60=compm3  n61=symetrieh  n62=symetriev  n63=symetriehc  n64=symetrievc  n65=convperim  n66=convarea  n67=fcons  n68=tag  n69=obj_pred_score  n70=score_dl  n71=kurt_mean  n72=skew_mean  n73=convperim_perim  n74=convarea_area  n75=symetrieh_area  n76=symetriev_area  n77=nb1_area  n78=nb2_area  n79=nb3_area  n80=nb1_range  n81=nb2_range  n82=nb3_range  n83=median_mean  n84=median_mean_range  n85=skeleton_area

[[7]]
n01=bx  n02=by  n03=width  n04=height  n05=area  n06=areai  n07=mean  n08=major  n09=minor  n10=feret  n11=area_exc  n12=thickr  n13=esd  n14=elongation  n15=range  n16=meanpos  n17=centroids  n18=cv  n19=sr  n20=perimareaexc  n21=feretareaexc  n22=perimferet  n23=perimmajor  n24=circex  n25=cdexc  n26=stddev  n27=mode  n28=min  n29=max  n30=x  n31=y  n32=xm  n33=ym  n34=perim.  n35=angle  n36=circ.  n37=intden  n38=median  n39=skew  n40=kurt  n41=%area  n42=xstart  n43=ystart  n44=fractal  n45=skelarea  n46=slope  n47=histcum1  n48=histcum2  n49=histcum3  n50=xmg5  n51=ymg5  n52=nb1  n53=nb2  n54=nb3  n55=compentropy  n56=compmean  n57=compslope  n58=compm1  n59=compm2  n60=compm3  n61=symetrieh  n62=symetriev  n63=symetriehc  n64=symetrievc  n65=convperim  n66=convarea  n67=fcons  n68=tag  n69=obj_pred_score  n70=score_dl  n71=kurt_mean  n72=skew_mean  n73=convperim_perim  n74=convarea_area  n75=symetrieh_area  n76=symetriev_area  n77=nb1_area  n78=nb2_area  n79=nb3_area  n80=nb1_range  n81=nb2_range  n82=nb3_range  n83=median_mean  n84=median_mean_range  n85=skeleton_area  n86=dl_score  n87=pi_score  n88=pi_percentage  n89=pi_counts  t01=dl_prediction

**Comment by jiho** [comment]
Les champs en commun à tous sont:

```
%area
angle
area
area_exc
bx
by
cdexc
centroids
circ.
circex 
compentropy
compm1
compm2
compm3
compmean
compslope 
convarea
convarea_area 
convperim
convperim_perim
cv
elongation
esd
fcons
feret
feretareaexc
fractal
height
histcum1
histcum2
histcum3
intden
kurt 
kurt_mean
major
max
mean
meanpos
median
median_mean
median_mean_range 
min
minor 
mode
nb1
nb1_area
nb1_range
nb2
nb2_area
nb2_range
nb3
nb3_area 
nb3_range
perim.
perimareaexc
perimferet
perimmajor
range
skelarea 
skeleton_area
skew
skew_mean
slope
sr 
stddev
symetrieh
symetriehc 
symetrieh_area
symetriev
symetrievc
symetriev_area
tag 
thickr
width
x
xm 
xmg5
xstart
y
ym
ymg5 
ystart
```

**Comment by picheral** [comment]
Validé
