### ISSUE TITLE
EcoPart: some detailed histograms cannot be computed

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#314]
For some profiles, the detailed histogram computation fails with the uninformative message "not all arguments converted during string formatting".

Example:
https://ecotaxa.obs-vlfr.fr/part/prj/92

Profiles:
`at38s1_5c1`
`at38s1c1`

**Comment by picheral** [comment]
La majeure partie des cas rencontrés a été expliquée par les investigations du LOV. Ces investigations peuvent encore être affinées. Tache affectée au LOV et sortie de 2.1.

**Comment by picheral** [comment]
Problème pas rencontré depuis très longtemps. Issue fermée.
