### ISSUE TITLE
Export DOI : Corriger les noms de dossier images

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#316]
Il faut utiliser les display_names pour être cohérent avec les fichiers TSV.

**Comment by picheral** [comment]
A FAIRE !!!

**Comment by laurent-n** [comment]
fait, mais remplacé le < par un _ car c'est un caractère spécial

**Comment by jiho** [comment]
Créer un dossier nommé `foo<bar` ne me pose aucun pb sous linux, mac OS. Est-ce un pb windows spécifique?

Il vaudrait peut–être mieux utiliser `__` plutôt que simplement `_` qui pourrait se retrouver pour d'autres raisons dans le nom n'est-ce pas?

**Comment by picheral** [comment]
Effectivement interdit sous Windows !
Le "_" est interdit dans la création de taxon par utilisateur et il n'y en a pas dans la taxo sur le serveur.
On garde un seul "_".
