### ISSUE TITLE
EcoPart: fonctionnaliser l'export

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#318]
Actuellement le code d'export[1] est un copier coller avec modifications mineures pour les différents cas. Cela mène à des oublis qui génèrent des bugs (Cf #317). Il faut le ré-écrire sous forme de fonction(s) avec chaque étape faite une seule fois à un seul endroit pour éviter de nouveaux bugs.

[1] https://github.com/oceanomics/ecotaxa_dev/blob/master/appli/tasks/taskpartexport.py

**Comment by grololo06** [comment]
Problème général, sera mis dans les contrôles qualité de la V3 avec un outil par exemple https://flake8.pycqa.org/en/latest/
