### ISSUE TITLE
Import data, Sample Id manquant

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#319]
Aujourd'hui, plusieurs projet contiennent des objets d'un seul sample. Le créateur des tables TSV d'import a indiqué pour chaque objet la latitude et la longitude... mais pas de sampleId. Le résultat est que ces données ne sont pas affichées sur les cartes (pas de lat/lon moyennées).
C'est une erreur du créateur des tables mais il n'y a pas de Warning à l'import ni de précision dans la doc "How to prepare data".
Il faudrait :
- Indiquer dans la page How to que le SampleId est important pour la visualisation des données sur les cartes
- Afficher un warning lors de l'import pour recommander de modifier les tables pour ajouter ce champ et proposer soit de continuer, soit d'abandonner

**Comment by picheral** [comment]
Exemples de projets:

https://ecotaxa.obs-vlfr.fr/prj/1986

https://ecotaxa.obs-vlfr.fr/prj/783

**Comment by grololo06** [comment]
A discuter entre nous pour clarifier. Dans ta proposition de dialogue utilisateur je ne vois pas trop quoi faire si l'utilisateur veut continuer. Créer des samples artificiels? De toutes façon on se dirige vers du "+ d'obligatoire".
Autre problème connexe, 2,4 millions d'objet n'ont pas de sample sur le site de production.

**Comment by jiho** [comment]
La solution déjà décidée pour ces objets orphelins est de créer un dummy sample. Il faudra que ce soit le cas à l'import également => règle le pb des objets sans sample.

Ensuite reste la question de comment/où est stockée l'info de lat-lon. Actuellement c'est au niveau obj avec une moyenne au niveau sample. On a dit que dans le futur ce serait au niveau pertinent (sample, subsample ou objet) avec un `COALESCE` pour associer une lat-lon à un objet quand celle-ci est au niveau sample ou subsample. Par contre je ne sais pas comment ça peut marcher dans l'autre sens (i.e. récupérer une lat-lon au niveau sample à partir des objets qu'il contient).

Mais je me dis que pour 2.4M sur 110M c'est pas super grave et que c'est probablement, bien souvent, des cas non pertinents (faux projets, imports de données de bino ou de photos en plongée, etc.). Je vois *un* cas pertinent: les engins tractés, pour lesquels on divise en sample qui ne sont pas un point mais un transect. Pour ceux là, le niveau pertinent pour lat-lon est l'objet, mais il est également pertinent qu'ils apparaissent sur une carte.
Deux possibilités:
- flag au niveau projet qui dit: "Compute lat-lon of sample as average of object data"
- on laisse l'utilisateur se démerder et choisir comment il associe une lat-lon à ses samples ;-)

**Comment by grololo06** [comment]
Grâce à #389, il y a maintenant un sample partout, éventuellement artificiel mais apte à recevoir des aggrégations.

**Comment by grololo06** [comment]
A partir de 2.5.0, la colonne est obligatoire et éventuellement remplie avec un "dummy" ID.
