### ISSUE TITLE
AMelioration interfaces et messages erreur import (selon Fabien !)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#323]
Bon.... je vois le bout du chemin mais j'en ai profiter pour bien faire le beta-testeur à fond des procédures de ré-import faites par quelqu'un de relativement extérieur à la construction intime d'ecotaxa

au nombre des choses a modifier:

sur les imports il serait important de rappeler le format exact du nom de fichier qui est attendu:

n'est mentionné qu'un fichier tsv (alors que ça marche aussi en txt.... et ça ça change le vie), certes le txt est mentionné dans "how to prepare data"

même chose sur le nom du fichier : (oui c'est mentionné dans le "how to prepare data") mais le message d'erreur devrait mentionner que le soucis viens du fait que le fichier ne l’appelle pas "ecotaxa_xxx.txt /tsv" et non pas un message laconique sur le nom des objets (qui font que l'on cherche toutes les mauvaises raisons à modifier plutôt que la plus évidente)

sur l'ajout de metadonnées aux échantillons:

il apparait (après moult tests) que la limite de nombre de metadonnées process/acq/sample soient toutes limitées à 30 chacune

=> ajout d'une description de cette limitation forte (que j'ai largement explosée) dans le "how to prepare data"

=> ajout d'un message d'erreur explicite "acq/process /sample data are overpassing the 30 limit"

pour le moment, le tsv est accepté en l'état (avec plus de 30 champs acq), les champs semblent ajoutés mais les données affichées sous forme de ??? (mais avec un bug d'importation qui m'a fait chercher toute l'après midi d’où l'erreur pouvait provenir dans mes fichiers)

L'erreur est aussi assez bizarre quand on cherche à re-exporter les données (re-export bugge)

=> mettre le message d'erreur en anglais?

Fabien

**Comment by grololo06** [comment]
Message spécifique rajouté dans le back-end pour l'excès de colonnes personnalisées. #7 et #322 pour les autres remarques. Le tout sera visible en 2.3.
