### ISSUE TITLE
"Pick from other projects" for the categories preset sometimes does not work

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#325]
Works with Laetitia (project admin on several projects); does not work (only shows "Loading") for Louis (project admin on one project but not on many).
Is it a problem of permissions? All viewable projects should be accessible through here.

**Comment by grololo06** [comment]
Tested using a non-admin user "Laurent Salinas pas admin" is OK and Louis says it works for him as well.
