### ISSUE TITLE
Outils Save filter et Apply saved filters

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#331]
Lorsque j'applique des filtres sur mon projet via l'onglet Other filters (par exemple en ne sélectionnant qu'un seul sample) et que je souhaite les sauvegarder pour pouvoir revenir sur mes filtres après avoir quitter mon projet rien ne se produit.

**Comment by grololo06** [comment]
Salut, ce bug est-il toujours d'actualité? Ca marche bien d'après mes essais.

**Comment by Elineau** [comment]
je reteste, je laisse passer qques heures entre mon filtre et son application, je te dirais 

__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 



De: "grololo06" <notifications@github.com> 
À: "oceanomics" <ecotaxa_dev@noreply.github.com> 
Cc: "Elineau" <elineau@obs-vlfr.fr>, "Assign" <assign@noreply.github.com> 
Envoyé: Mardi 26 Mai 2020 15:40:47 
Objet: Re: [oceanomics/ecotaxa_dev] Outils Save filter et Apply saved filters (#331) 





Salut, ce bug est-il toujours d'actualité? Ca marche bien d'après mes essais.

**Comment by grololo06** [comment]
Salut, tu as eu le souci à nouveau?

**Comment by jiho** [comment]
@Elineau tu peux retester? Ça marche pour moi aussi. Je ferme, il faudra réouvrir si besoin.
