### ISSUE TITLE
EcoPart: Simplify depth_offset

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#333]
Curent depth offset is in `part_projects.default_depthoffset` and in `part_samples.acq_depthoffset` + is not available in EcoTaxa tables while the depth is not corrected.

I suggest to:

1. set a default value per project while entering the metadata (to avoid having to type it in for each sample) but store the value for each sample and not at project level, for simplicity
2. correct depth records before import in EcoTaxa.

**Comment by picheral** [comment]
La règle est précisée dans la page metadata project d'EcoPart et me convient.

**Comment by jiho** [comment]
Le fait d'avoir des profondeurs corrigées d'un côté et pas de l'autre n'est quand même pas très heureux.

Par ailleurs, existe-t-il un cas où le depth offset est différent entre les samples d'un même projet? Je ne l'ai pas trouvé. Si ce n'est pas le cas, il n'est pas nécessaire de le garder aux deux endroits.

Dans tous les cas, il faudra faire attention à ce que les gens ne puissent pas récupérer des données biaisée par l'API. Actuellement, quand je tape dans les bases, je récupère des choses non cohérentes.
