### ISSUE TITLE
FTP vs Local Importation : symbol non importé

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#334]
Par FTP nous e pouvons pas importer de sample ayant dans leurs noms un symbole (ex : 200µm).
Par l'import local cela marche très bien pourtant

**Comment by grololo06** [comment]
Bonjour, j'ai un peu du mal à voir de quoi il s'agit. Pourriez-vous joindre un fichier ou me donner son nom sur le FTP? 
Merci.

**Comment by Elineau** [comment]
Salut Laurent, 
Voici un exemple : /Ecotaxa_Data_to_import/ZOOSCAN_Universite_Toulon/Zooscan_zooscan_rade_toulon_apstein_200/_work

**Comment by grololo06** [comment]
Salut,
Quand tu dis "par l'import local", ca veut dire en utilisant ecotaxa portable? Ou en envoyant un zip sur le serveur?
Merci.

**Comment by picheral** [comment]
ZIP sur le serveur. Pas d'utilisation instance mobile Windows pour cette issue.

**Comment by Elineau** [comment]
dans les murs du labo 

__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 



De: "grololo06" <notifications@github.com> 
À: "oceanomics/ecotaxa_dev" <ecotaxa_dev@noreply.github.com> 
Cc: "Elineau" <elineau@obs-vlfr.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 30 Avril 2020 09:40:29 
Objet: Re: [oceanomics/ecotaxa_dev] FTP vs Local Importation : symbol non importé (#334) 





Salut, 
Quand tu dis "par l'import local", ca veut dire en utilisant ecotaxa portable? Ou en envoyant un zip sur le serveur? 
Merci.

**Comment by grololo06** [comment]
J'essaie de résumer ce qui s'est passé:
1. Il y a un .zip sur un PC sous Windows.
2. Le .zip a été extrait sur le PC Windows.
3. Le répertoire résultant de l'extraction a été copié sur le FTP plankton en utilisant ??? (filezilla?)
4. Le répertoire FTP a été utilisé pour un import EcoTaxa, option "Choose a folder or zip file on the server"
5. Ca a planté, objet de la présente issue.

En faisant un import EcoTaxa avec l'option "Upload folder(s) compressed as a zip file" et en envoyant le même .zip, ça marche.

Merci de me corriger ou de confirmer.

**Comment by Elineau** [comment]
je vais retester 

__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 



De: "grololo06" <notifications@github.com> 
À: "oceanomics" <ecotaxa_dev@noreply.github.com> 
Cc: "Elineau" <elineau@obs-vlfr.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 30 Avril 2020 10:51:19 
Objet: Re: [oceanomics/ecotaxa_dev] FTP vs Local Importation : symbol non importé (#334) 





J'essaie de résumer ce qui s'est passé: 

    1. Il y a un .zip sur un PC sous Windows. 
    2. Le .zip a été extrait sur le PC Windows. 
    3. Le répertoire résultant de l'extraction a été copié sur le FTP plankton en utilisant ??? (filezilla?) 
    4. Le répertoire FTP a été utilisé pour un import EcoTaxa, option "Choose a folder or zip file on the server" 
    5. Ca a planté, objet de la présente issue. 


En faisant un import EcoTaxa avec l'option "Upload folder(s) compressed as a zip file" et en envoyant le même .zip, ça marche. 

Merci de me corriger ou de confirmer.

**Comment by Elineau** [comment]
Sur FileZilla : /Ecotaxa_Data_to_import/ZOOSCAN_Universite_Toulon/Zooscan_zooscan_rade_toulon_apstein_200/_work 

Quand j'importe le work dans un projet, il me met l'erreur ci dessous, car il ne lit pas le symbole "µm" quand il va checker la table .tsv et non pas parce qu'il manque des lignes dans la table. Donc ce n'est pas une question de zip là. 


















__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 



De: "Amanda Elineau" <amanda.elineau@imev-mer.fr> 
À: "oceanomics" <reply@reply.github.com> 
Cc: "oceanomics" <ecotaxa_dev@noreply.github.com>, "Elineau" <elineau@obs-vlfr.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 30 Avril 2020 11:00:38 
Objet: Re: [oceanomics/ecotaxa_dev] FTP vs Local Importation : symbol non importé (#334) 

je vais retester 

__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 


De: "grololo06" <notifications@github.com> 
À: "oceanomics" <ecotaxa_dev@noreply.github.com> 
Cc: "Elineau" <elineau@obs-vlfr.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 30 Avril 2020 10:51:19 
Objet: Re: [oceanomics/ecotaxa_dev] FTP vs Local Importation : symbol non importé (#334) 






J'essaie de résumer ce qui s'est passé: 

    1. Il y a un .zip sur un PC sous Windows. 
    2. Le .zip a été extrait sur le PC Windows. 
    3. Le répertoire résultant de l'extraction a été copié sur le FTP plankton en utilisant ??? (filezilla?) 
    4. Le répertoire FTP a été utilisé pour un import EcoTaxa, option "Choose a folder or zip file on the server" 
    5. Ca a planté, objet de la présente issue. 



En faisant un import EcoTaxa avec l'option "Upload folder(s) compressed as a zip file" et en envoyant le même .zip, ça marche. 

Merci de me corriger ou de confirmer.

**Comment by grololo06** [comment]
Il y a des soupçons qui se confirment sur FileZilla ou le serveur FTP.
Dans` /Ecotaxa_Data_to_import/TestLaurentS`, j'ai transféré 2 fichiers, l'un à partir de mon PC linux, l'autre à partir de ma VM windows, avec le signe micron dedans.
FileZilla sous linux affiche:
![Capture d’écran de 2020-04-30 18-06-15](https://user-images.githubusercontent.com/20199778/80733133-92af0200-8b0d-11ea-951e-f14ebd338991.png)
FileZilla sous Windows affiche:
![Capture d’écran de 2020-04-30 18-08-58](https://user-images.githubusercontent.com/20199778/80733292-cb4edb80-8b0d-11ea-9196-b037d9d6054d.png)
Par contre le répertoire sur la machine newecotaxa contient:
![Capture d’écran de 2020-04-30 18-10-44](https://user-images.githubusercontent.com/20199778/80733421-f9ccb680-8b0d-11ea-8792-d43c34fbb094.png)

**Comment by grololo06** [comment]
Les zips recrées à partir du serveur FTP sont dans plankton:/zooscan_w/work

**Comment by grololo06** [comment]
Il y a un réglage FileZilla:
![Capture d’écran de 2020-04-30 18-54-39](https://user-images.githubusercontent.com/20199778/80737685-2b488080-8b14-11ea-9f24-a528d8c3f7f2.png)
Il faut le forcer à UTF-8 s'il y a des caractères spéciaux. => Doc
Il faut aussi détection des fichiers avec un mauvais charset pour un meilleur message=> Code import

**Comment by grololo06** [comment]
Code fixed and validated by users, doc. updated.
