### ISSUE TITLE
Bug dans import/export - champs latitude et longitude

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#340]
Lors de l'export on envoie dans le TSV le contenu quasi brut des colonnes dans la DB, par exemple:
'latitude': 18.0, 'longitude': -24.4166666666667
Lors de l'import le code 2.2 considère qu'il faut convertir en degré decimaux, donc l'objet se retrouve avec:
'latitude': 18.0, 'longitude': -24.6944444444445

Trouvé pendant mes tests sur le back-end, je me sers d'un fichier exporté comme source de test.

**Comment by grololo06** [comment]
Il semble que le bug ne soit pas sur le site de production.

**Comment by laurent-n** [comment]
Dans version 2.1
ConvDegreeMinuteFloatToDecimaldegre est uniquement dans uvp_sample_import.py pour traiter les fichiers headers des samples UVP de Ecopart.
Cette fonction à été enrichie pour supporter la notataion dd°mm.ss comme alternative
Puis cette fonction à été réutilisée à tort pour traiter l'import des lat/long des objets qui peuvent être soit en degrés décimaux soit en notation dd°mm.ss
