### ISSUE TITLE
create a new taxa don't appear in the preview mode

### ISSUE THREAD

**Issue by fabienlombard** [oceanomics/ecotaxa_dev#342]
the "create new taxa" option don't appears when classifying under the preview mode

**Comment by grololo06** [comment]
Hello,
For an EcoTaxa rookie like me :) , how to activate the "preview mode" you mention?
Thx.

**Comment by fabienlombard** [comment]
(the little eye on top of each images)

**Comment by grololo06** [comment]
In "objectdetails" popup, the dropbox to set a new classification is visually identical to the one in the main page, but small link "Create new category" does not appear when a needed category is absent.

**Comment by grololo06** [comment]
It's also a bug as MRU list does not appear there.

**Comment by grololo06** [comment]
Fixed for 2.4.4
