### ISSUE TITLE
EcoPart: Division by 0 error when drawing graph for a single sample

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#347]
To reproduce:
- Select a single sample on the map (CTRL+drag)
- Click on "Draw graph" button
There is a python error where the graph should be.
I agree the graph is a bit useless for a single sample...

**Comment by laurent-n** [comment]
Je ne rencontre pas de problèmes.
Préciser quel graphe il est dessiné sur quel sample de quel projet.

**Comment by grololo06** [comment]
C'était "n'importe lequel" mais c'était aussi sur la 2.1. Je ferme.
