### ISSUE TITLE
Serious bug when merging projects

### ISSUE THREAD

**Issue by rkiko** [oceanomics/ecotaxa_dev#350]
I yesterday created subsets from some of our generic projects and merged them. I got a small warning that the „mapping“ of projects is not identical, but could proceed. Turns out that the result is that some data fields like area, major, minor and mean are switched around.

Merging of projects should not be possible if the mapping is not identical, if the result is such a problem. Please exchange the warning against an error.

**Comment by grololo06** [comment]
Hi,
The merge page says:
" If object data are not consistent between both projects :
    New data fields are added to the Current project
    The resulting project will thus contain partially documented datafields. "
It's for sure not the case, from source code => Bug

**Comment by jiho** [comment]
@rkiko can you elaborate on "switched around", what to you mean exactly? Can you give the link to the project on EcoTaxa?
If it's just that the order of the fields is changed, this is expected. If the content of the fields are mixed up, this is a bug.

**Comment by rkiko** [comment]
I generated new subsets from

https://ecotaxa.obs-vlfr.fr/prj/358 (sample m105_mn02_n1_lrg)

and

https://ecotaxa.obs-vlfr.fr/prj/528 (sample msm22_mn03_n1_lrg) 


and merged them in
https://ecotaxa.obs-vlfr.fr/prj/2996


I get the warning that the mapping is different:

<img width="612" alt="Bildschirmfoto 2020-04-18 um 16 13 04" src="https://user-images.githubusercontent.com/6485104/79640290-14f40980-8191-11ea-9977-c626be0e5dbd.png">


Screenshots attached show that mean = 180 is changed to a mean of 464 for the Euphausiid from sample m105_mn02_n1_lrg)


<img width="1037" alt="Bildschirmfoto 2020-04-18 um 16 33 11" src="https://user-images.githubusercontent.com/6485104/79640570-939d7680-8192-11ea-9cad-b8ecf4827e41.png">



<img width="1123" alt="Bildschirmfoto 2020-04-18 um 16 23 26" src="https://user-images.githubusercontent.com/6485104/79640317-3bb24000-8191-11ea-81b1-071c905d1be0.png">


The position of the value is maintained, but the annotation is changed. E.g. mean becomes mode and height becomes mean. So, the values are switched around (or rather the annotations), which is fatal.


Values in the msm22 samples seem unchanged. I merged the M105 data into the MSM22 Dataset.


<img width="1119" alt="Bildschirmfoto 2020-04-18 um 16 22 59" src="https://user-images.githubusercontent.com/6485104/79640342-643a3a00-8191-11ea-83c7-2573866723b9.png">


<img width="1116" alt="Bildschirmfoto 2020-04-18 um 16 11 57" src="https://user-images.githubusercontent.com/6485104/79640344-69978480-8191-11ea-9945-28fe9cf40575.png">


If you find a way to fix this after the fact, I would be very grateful to know. Otherwise, I have to find and upload the data again ..

**Comment by grololo06** [comment]
Thanks for the data.
If I sum up, we now have, in project (subset) 2996:
      
-  exactly 411 objects, all in sample "m105_mn02_n1_lrg" and coming from defunct subset project 2995,  having shuffled values. 
-  110 objects, all in sample "msm22_mn03_n1_lrg", which are correct.

From the code, and as you saw, the receiving project imposes its "mappings" and the source project "mappings" are just ignored.

I can do some magic SQL to un-shuffle the 411 objects on the DB, as, fortunately, using the sample we know exactly, in your case, where the problematic data is. 
Another option coming to me (not tried!) is export/re-import.
Maybe @jiho has another idea.

**Comment by rkiko** [comment]
I just created project 2996 to document and recreate the error. It can be used to try fixing the problem, but the original data is OK. 

I have other three other projects where a fix is needed. I would need to figure out exactly how the magic needs to be applied to these ;)

Otherwise, I could download, fix the data and reupload.

Main step right now would be to disable the possibility to merge projects/subsets that do not have the same mapping. Next step would be to fix the functionality. Obviously, it would be necessary to match the mapping, not force one on the other.

**Comment by grololo06** [comment]
> I have other three other projects where a fix is needed. I would need to figure out exactly how the magic needs to be applied to these ;)

There is no simple fix for general case AFAIK. However I can have a look at the projects.

> Main step right now would be to disable the possibility to merge projects/subsets that do not have the same mapping. Next step would be to fix the functionality. Obviously, it would be necessary to match the mapping, not force one on the other.

Agreed, I just entered #352

**Comment by grololo06** [comment]
Not possible anymore in 2.4. The merge takes care about "free fields", additions them from source into destination, re-shuffles the values if they are in different DB columns, and refuses to do if there is an overflow. This applies to object, sample, acquisition and process entities.
