### ISSUE TITLE
Forbid merge when projects mapping is different.

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#352]
As a quick first step to fixing #350, we have to forbid merge operations when mapping is different, as it results in a potential loss of important data.

**Comment by grololo06** [comment]
It's safe to merge if source project has no mapping at all, but other than this case it should be forbidden.

**Comment by jiho** [comment]
Also safe when the two mappings are exactly identical.

**Comment by grololo06** [comment]
Better fix in 2.4, with different but compatible fields it's possible to merge, as long as there is space left in destination project.
