### ISSUE TITLE
Unités dans Export ECOPART

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#356]
La profondeur indiquée aujourd'hui "Depth [m]" doit être "Pressure [db]" comme dans tout EcoPart (filtres et graphes en particulier).

**Comment by grololo06** [comment]
Ca m'a pas l'air compliqué, y-a-t'il une formule de conversion?

**Comment by picheral** [comment]
Pas de formule ! Juste changement de label !!!

**Comment by picheral** [comment]
On change DEPTH en PRESSURE dans tout ce qui est visible (interface) mais pas dans l'export pour ne pas changer les fichiers. Ce changement final sera fait lors de la refonte d'EcoPart au même moment qu'une normalisation plus profonde de la nomenclature.
