### ISSUE TITLE
Set default encoding in the whole application to utf8 on all platforms

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#365]
In order to avoid future occurrences of e.g. #364: Given that:
-  most of the manual testing is NOT done on Linux boxes
- production server is a Linux

=> We must force somehow the python encoding, even on Windows/MacOS/whatever, to utf8.

Ideas (to try!) from https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python

**Comment by grololo06** [comment]
Something like:
`import os
os.environ["PYTHONIOENCODING"] = "utf8"
`
In runserver.py, should do the trick. 
For maximum security: Enclose in a kind of "if I'm on Windows" condition, and check it's really taken into account for portable editions.
Can be tested by removing a recently added encoding='latin_1', in a dev environment.

**Comment by laurent-n** [comment]
Cette variable n'as pas d'effet sur la lecture des fichier(testé)
d'après le doc c'est que sur stdin/out/err
d'aprés la doc de open sur le parametre encoding
The default encoding is platform dependent

Je propose donc de continuer à spécifier explicitement l'encodage du fichier lors de son ouverture.

**Comment by grololo06** [comment]
There is no easy solution so far, maybe https://www.python.org/dev/peps/pep-0597/ in the future would help.
