### ISSUE TITLE
IMPORT images UVP6 dans ECOTAXA

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#369]
Actuellement on doit sélectionner le répertoire ECODATA ou ses sous répertoires dans lequel se trouve le ZIP.
Faire en sorte qu'on sélectionne le projet (racine du projet) comme lors de l'import ECOPART et ceci seulement pour les projets UVP6. Mettre à jour la doc sur la page.
Alternative : créer un IMPORT Images UVP6 qui serait très simplifié.

**Comment by grololo06** [comment]
Ca m'a l'air bon non? Il manque quoi?

**Comment by picheral** [comment]
L'idée est de créer le projet dans EcoPart et que l'import Ecopart importe automatiquement les images dans le projet correspondant plutôt que d'avoir à ouvrir ce projet, choisir le répertoire manuellement et importer les images !

**Comment by grololo06** [comment]
Par exemple avoir dans EcoTaxa un répertoire d'import par défaut, ou se souvenir de la valeur précédente.

**Comment by picheral** [comment]
remplacé par #374
