### ISSUE TITLE
Review database field names

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#373]
Should follow the [DarwinCore](https://dwc.tdwg.org/terms/) reference and be consistent with the [OBIS data format](https://obis.org/manual/dataformat/).
When possible, use the [BODC vocabulary](http://vocab.nerc.ac.uk/), in particular the [OBIS collection](http://vocab.nerc.ac.uk/collection/Q01/current/), the [P01 vocabulary](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/P01/) for variables (see the [parameter usage guide](https://www.bodc.ac.uk/resources/vocabularies/parameter_codes/) too), the [P06 vocabulary](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/P06/) for units.

Specifications to come.

**Comment by picheral** [comment]
Barcode is very usefull to link with the plankton collection as an example. It would be relevant in the context of the development of a management app for the CCP.

**Comment by grololo06** [comment]
We cannot stick to DwC for storing data, which is _extemely_ redundant and space consuming. Adopting their naming convention would be more confusing as future developpers might assume it's the same concept when it's not in many occasions.
#326 to expand instead.
