### ISSUE TITLE
EcoPart :  les metadata ne se mettent pas correctement à jour lors import UVP6

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#378]
- importation de sample dans EcoPart (projet 214, Id 20703 et Id 20704), vérification des "UVP settings" Aa et Exp. 
- remove samples car ces metadata sont erronées...
- correction des metadata dans les données à importer (int_b_ca_Particule.zip et int_bb_Particule.zip)
- re-import des mêmes samples => les valeurs de Aa et Exp ne changent pas !!!!

**Comment by picheral** [comment]
Je pense avoir compris... Vérifications supplémentaires en cours

**Comment by picheral** [comment]
L'erreur vient du fait que les metadata sample sont lues dans le fichier header (du répertoire meta) et non dans l'archive ZIP du répertoire EcoData qui est pourtant self contained et comprend toutes les metadata et data utiles. 
Nous travaillons actuellement sur des étalonnages et ceux-ci impliquent des modifications à postériori de ces metadata que l'utilisateur habituel n'a pas à faire.

**Comment by picheral** [comment]
Il est au minimum nécessaire de clarifier ce qui se passe dans la page d'import des samples. Ceci doit être détaillé à partir du code.

**Comment by picheral** [comment]
Exemple : https://ecotaxa.obs-vlfr.fr/Task/Create/TaskPartZooscanImport?p=233

**Comment by laurent-n** [comment]
Les données suivantes sont lu dans le metadata.ini qui est dans le xxxx_Particule.zip
Shutter, Gain, Threshold, Pressure_offset
Vignetting_lower_limit_size qui est intégré avec aa&Exp pour calculer smzoo
Limit_lpm_detection_size qui est intégré avec aa&Exp pour calculer smbase
Les autres données telles que aa, Exp, PixelSize,VolImage,FirstImage sont lues dans le fichier header comme c'était fait pour UVP5
ça peut introduire des incoherence avec le contenu du zip, mais simplifier des corrections qui du coup ne requièrent pas de regenerer les zip.
A vous de me dire ce qu'on fait du coup (A minima l'écrire sur la page je suppose)

**Comment by picheral** [comment]
On ne fait RIEN dans l'immédiat SAUF ECRIRE ce qui est fait sur la page et cela tant que la chaine de metadata n'est pas clarifiée pour EcoTaxa, EcoPart, Zooprocess, UVPapp !!!!
