### ISSUE TITLE
Augmenter le nombre de pixels de déplacement avant de commencer un drag afin de faciliter la sélection d'objets

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#383]
Il faut cliquer dans un espace précis de la vignette pour la sélectionner sinon ça ne fonctionne pas.
Cela se reproduit facilement quand on fait une multiple sélection très rapide (sélectionner plusieurs vignettes une après l'autre sur 1 ligne par exemple) sans regarder où on clique sur les vignettes. 
A voir si on peut améliorer cela.

**Comment by grololo06** [comment]
Je pense que c'est + lié au déplacement de la souris pendant le click qu'à un emplacement particulier dans les vignettes. 
A essayer: cliquer sans arrêter la souris, il ne devrait pas y avoir de sélection.

**Comment by grololo06** [comment]
@Elineau il faudrait passer un peu de temps à caractériser le problème, pour qu'on puisse s'y attaquer.

**Comment by jiho** [comment]
C'est clairement le déplacement de la souris. Toute la vignette (en faut toute la zone grisée autour de la vignette) est cliquable. Je ne vois pas comment ça pourrait marcher autrement vu le code actuel: les propriété de cliquabilité sont sur le `<div>` qui est coloré.

Je change le titre.

**Comment by grololo06** [comment]
@Elineau on prend RDV pour une démo du problème?

**Comment by grololo06** [comment]
OK après analyse du problème:
- L'image est "naturellement" draggable dans le browser, toute image sur une page Web l'est. On n'a aucun contrôle sur le délai
- On installe un jQuery 'draggable' sur le cadre autour
jQuery essaie de mixer convenablement les évènements drag de l'image et ce qu'il installe sur le cadre...

**Comment by grololo06** [comment]
Corrigé pour la 2.4.3

**Comment by jiho** [comment]
👏
