### ISSUE TITLE
Page PREDICTION : mettre une map avec filtre par instrument associé

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#385]
J'ai un nouveau projet que j'aimerai prédire. Je suis donc intéressé par les autres projets qui ne m'appartiennent pas et dont je n'ai pas d'accès mais que j'ai le droit d'utiliser pour prédire mon projet.
J'ai donc besoin de rechercher un projet ayant le même instrument que le mien + qui se trouve dans la même zone géographique que mon projet.
Aujourd'hui nous pouvons filtrer les projets de prédiction par l'instrument, par le nom du projet mais pas par la zone géo.

**Comment by grololo06** [comment]
Sans avoir une carte, on peut spécifier une zone e.g. "100 miles autour du projet actuel".

**Comment by jiho** [comment]
Je suis assez convaincu que (1) sur une bonne partie du globe la date compte plus que la localisation, (2) la meilleure solution est un modèle unique, grand, pour démarrer et une auto prédiction ensuite.

Du coup, jolie idée mais je ne pense pas que ça vaille le coup.

**Comment by picheral** [comment]
A documenter dans l'interface de prédiction => expliquer la stratégie recommandée pour tirer le meilleur de l'app.

**Comment by Elineau** [comment]
Pas de discussion donc.Je suis assez étonné qu'un modèle mixant tous (et ce n est pas tous mais 3 projets) les projets du monde entier soit plus efficace qu' un projet voisin en terme de temps et de zone geo. Cela signifierait qu' il est plus intéressant d utilisant le modèle zooscan pour prédire le point b à la place du point b ou dyfamed ?Si c est le cas, il est donc prévu de faire des modèles pour chacun des instruments d'imagerie existant dans ecotaxa ?Amanda
-------- Message d'origine --------De : picheral <notifications@github.com> Date : 10/09/2020  08:30  (GMT+01:00) À : oceanomics/ecotaxa_dev <ecotaxa_dev@noreply.github.com> Cc : Elineau <elineau@obs-vlfr.fr>, Author <author@noreply.github.com> Objet : Re: [oceanomics/ecotaxa_dev] Page PREDICTION : mettre une map avec filtre par instrument associé (#385) 

A documenter dans l'interface de prédiction => expliquer la stratégie recommandée pour tirer le meilleur de l'app.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/oceanomics/ecotaxa_dev/issues/385#issuecomment-690019190",

"url": "https://github.com/oceanomics/ecotaxa_dev/issues/385#issuecomment-690019190",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jiho** [comment]
Un modèle entrainé sur un gros training set avec des images venant d'un peu partout sera meilleur qu'un modèle entrainé sur un petit training set similaire au projet d'intérêt (principalement parce que définir "similaire" est compliqué).

Ensuite, après les premières prédictions et validation, le meilleur training set adapté au projet est le projet lui même.

En fait, il est même probable que le gros modèle universel reste meilleur et on en a fait un par instrument; la difficulté actuelle est que ces gros modèles sont inutilisables car trop longs à charger.
