### ISSUE TITLE
Add `barcode` as a preset field at `sample` level

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#39]

**Comment by jiho** [comment]
barcode is not a DarwinCore or BODC field, so we have no predefined name to give it.

It is a text field (barcodes are not just numbers) so there is no reason to optimise a db field for it (or maybe just on the length of the field)

The only reason to make it a predefined field would be:
- to be able to query on it across projects (unlikely to be very useful)
- to put an index on it and query this faster

Is that really relevant? @picheral can you give a use case that would make this worthwhile?

Closing this for now. Will be discussed as part of the review of the whole db field names. Can be reopened if needed.

**Comment by jiho** [comment]
To be solved as part of #373
