### ISSUE TITLE
Vignettes qui restent prédites après validation

### ISSUE THREAD

**Issue by Kikouliou** [oceanomics/ecotaxa_dev#391]
Je viens de valider une partie des vignettes dans la catégorie "scale". Après mon ctrl+s, je me retrouve avec les mêmes vignettes prédites, dont celles que je viens juste de valider. Pourtant, dans la colonne de gauche, il m'en compte moins. Je me retrouve à devoir valider une deuxième fois les mêmes vignettes, même après avoir rafraîchi la page. Ce problème est survenue trois fois avec moi.
![Sans titre](https://user-images.githubusercontent.com/33952113/81276300-58c88900-9042-11ea-91a2-b7591f3d3301.png)

**Comment by grololo06** [comment]
Précisions: Les 3 fois se sont étalées sur quelques semaines. L'occurence présente du problème est survenue juste avant la création de la présente Issue.

**Comment by grololo06** [comment]
Diagnostic sur le serveur:

Dans le fichier de log `ecotaxa_uwsgi.log.1588847553`, à la marque horaire '[2020-05-07 10:07:32,749]' il y a une trace contenant `[[46665092, 46665110, 46665903, 46666132, 46666221, 46666257, 46666263, 46666305,` et démarrant une série de 500 object IDs uniques.

Sur ces 500 objets, seuls 69 ont été classifiés le "2020-05-07 10:07:33.466323" (p.e. 46776388 et 46776646). Les autres ont été classifiés le "2020-05-13 16:14:57.688274".

Pour ces 500 objets, aucun historique de classification (à supposer qu'il soit correct) n'est postérieur au 4 Mai.

Il semble donc que l'interface Web se soit comportée correctement en envoyant les objets à classifier, mais que le serveur n'ait fait qu'une mise à jour partielle, interrompue.

On note la présence dans les fichiers journaux de 5 tasks (31322, 31323, 31332, 31333, 31334) dont on ne peut pas exclure qu'elles aient influencé le comportement.

Certains fichiers de log (serveur Web) ayant été perdus, merci de m'avertir si le bug survient à nouveau.

**Comment by grololo06** [comment]
Autre occurence:
![image](https://user-images.githubusercontent.com/20199778/83638057-dc758700-a5a8-11ea-83a5-9f4548e7532b.png)

En faisant "Recalc count", le compte erroné sur la gauche revient aux 843 attendus.
Confirmé dans une autre session, autre utilisateur.
Selon uwsgi.log, l'objet 46714264 est censé avoir reçu une ligne d'historique mais rien n'apparataît dans Object details.

**Comment by grololo06** [comment]
Fixé (jusqu'à preuve du contraire) pour v2.3.3
