### ISSUE TITLE
Nom de l'instrument dans création d'un nouveau projet

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#392]
Pourrait on forcer la saisie du nom de l'instrument en début de nom de projet ?

**Comment by laurent-n** [comment]
Je pense que le mieux serait que ça soit une métadonnée du projet, un peu comme les projet particules et le faire apparaître dans la liste des projets

**Comment by Elineau** [comment]
Cela existe pour zooscan uvp et flowcam car c est le logiciel zooprocess qui est utilisé pour créer les tables .tsvPour tous les autres instruments la metadata "instrument" n est pas obligatoire.Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Message d'origine --------De : laurent-n <notifications@github.com> Date : 07/05/2020  12:31  (GMT+01:00) À : oceanomics/ecotaxa_dev <ecotaxa_dev@noreply.github.com> Cc : Elineau <elineau@obs-vlfr.fr>, Author <author@noreply.github.com> Objet : Re: [oceanomics/ecotaxa_dev] Nom de l'instrument dans création d'un nouveau projet (#392) 

Je pense que le mieux serait que ça soit une métadonnée du projet, un peu comme les projet particules et le faire apparaître dans la liste des projets



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/oceanomics/ecotaxa_dev/issues/392#issuecomment-625170779",

"url": "https://github.com/oceanomics/ecotaxa_dev/issues/392#issuecomment-625170779",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jiho** [comment]
Instrument sera un champ obligatoire au niveau projet dans la prochaine version de la db.

**Comment by grololo06** [comment]
Il faudra s'occuper des contrôles de cohérence. Par exemple doit-on rejeter un import si l'instrument n'est pas celui du projet? Ou un merge?
Pour l'instant l'instrument est au niveau acquisition, en allant voir dans la DB on trouve quelques projets bi-instrument et quelques projets sans instrument:
`select count(distinct instrument), projid from acquisitions group by projid order by 1 desc`

**Comment by jiho** [comment]
Il est nécessaire que les projets soient instrument spécifique (Cf #264).

Pour les cas compliqués (pas d'instrument ou instruments différents, il faudra les résoudre à la main).

Une fois enregistré comme un champ au niveau projet, on pourra l'afficher comme on veut.

Pour le contrôle de cohérence, ce sera difficile à part si on force, dans le format d'import, un champ pour vérifier cette cohérence. Mais on peut espérer que si le champ instrument est explicite au niveau projet, les gens ne seront pas couillon d'importer de l'IFCB dans un projet ZooScan. Je ne pense pas qu'on puisse faire bcp mieux.

**Comment by grololo06** [comment]
A fusionner avec #264

**Comment by jiho** [comment]
La solution est en effet #264 et #182. Je ferme celle-ci.
