### ISSUE TITLE
Delete objects (purge) function should be optimized or become a task

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#394]
Looking at the logs I see lots of purge requests lasting more than 60s, up to 3000s. 
Not sure that during this time, the user did not start re-using the project somehow, with nasty consequences on data consistency.

**Comment by picheral** [comment]
Il y a une issue sur le problème du délais de purge #324

**Comment by grololo06** [comment]
Problèmes techniques à la source:
- Les delete d'objet sont tous dans la même transaction BDD -> très grosse pour de gros projets
- Il n'y a pas d'index permettant à PG de vérifier les clefs étrangères lors de la suppression des process/acquisition. Il y a un index sur sample seulement.

**Comment by grololo06** [comment]
Done for 2.4.2. Fast enough, around 10K objects/sec, for remaining interactive.
