### ISSUE TITLE
Filtrage impossible

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#395]
Bug sur le projet m148 où il est impossible de filtrer, a priori, par un nombre trop important de profils

![image](https://user-images.githubusercontent.com/18468240/81530978-33998a80-9362-11ea-988a-a61d0d4aa9d6.png)

**Comment by grololo06** [comment]
Les préférences sont stockées, par utilisateur, mais pour _tous_ les projets, dans une seule colonne de la DB. Le problème n'est donc pas spécifique à un projet en particulier.

**Comment by grololo06** [comment]
Pour chaque projet de l'utilisateur dans la copie d'écran, voici le nombre de samples dans les préférences:
`[(4, 36),
 (22, 335),
 (28, 0),
 (30, 36),
 (35, 24),
 (36, 34),
 (37, 1024),
 (38, 64),
 (40, 74),
 (41, 0),
 (42, 0),
 (43, 542),
 (45, 0),
 (50, 59),
 (56, 0),
 (71, 0),
 (107, 0),
 (109, 0),
 (110, 124),
 (122, 914),
 (133, 191),
 (146, 137),
 (149, 995),
 (156, 5),
 (256, 0),
 (257, 0),
 (327, 0),
 (330, 0),
 (332, 0),
 (351, 755),
 (499, 0),
 (507, 0),
 (548, 0),
 (556, 0),
 (558, 233),
 (559, 437),
 (560, 0),
 (563, 0),
 (578, 0),
 (579, 4337),
 (584, 383),
 (585, 0),
 (586, 0),
 (589, 491),
 (593, 677),
 (594, 0),
 (595, 689),
 (602, 47),
 (603, 35),
 (620, 0),
 (622, 0),
 (627, 5),
 (637, 0),
 (667, 0),
 (801, 0),
 (802, 0),
 (825, 0),
 (853, 5),
 (855, 77),
 (1165, 41),
 (1252, 5),
 (1286, 137),
 (1342, 0),
 (1537, 0),
 (1591, 0),
 (2159, 0),
 (2192, 5),
 (2193, 0),
 (2247, 0),
 (2485, 62),
 (2808, 104)]
` 
On peut récupérer de la place en supprimant les préférences sur les vieux projets p.e. 33 ou 37 ?

**Comment by laurent-n** [comment]
il me semble qu'il y a une purge pour ne garder que les n plus récents projets

**Comment by grololo06** [comment]
Effectivement, on ne garde que les n plus récentes préférences, mais dans ce cas, même les plus récentes débordent les 40K de taille de colonne.

**Comment by grololo06** [comment]
Fixed for 2.3.
