### ISSUE TITLE
No visible vignette on manual classification screen

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#402]
User witnesses:
- no vignette appears at first
- they appear after a while, typically 10-20s
![no_vignette](https://user-images.githubusercontent.com/20199778/81906365-6c399e00-95c6-11ea-9c90-ce0db38c40c0.png)
Tech notes:
- The time in the screenshot is UTC
- The nginx service was restarted today as part of upgrade to 2.3
- DB statistics and vaccum was done on large tables

**Comment by Kikouliou** [comment]
![image](https://user-images.githubusercontent.com/33952113/81907031-b024a700-95b6-11ea-921e-1a43c3a37821.png)

**Comment by grololo06** [comment]
It also happens frequently around 4-5PM

**Comment by Kikouliou** [comment]
Aussi, si nous sommes sur une page avec des vignettes assignées puis que nous faisons un ctrl+s, les vignettes n'apparaissent pas après la sauvegarde. Elles n'apparaissent que si nous bougeons la roulette de la souris. Ceci est reproductible.

**Comment by grololo06** [comment]
Due to https://github.com/eisbehr-/jquery.lazy/issues/229 that I just entered.

**Comment by grololo06** [comment]
Move to a newer version of jquery lazy which has entry points for cleanup of instances. Use the API.
