### ISSUE TITLE
ECOPART : problème affichage des graphes

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#403]
![image](https://user-images.githubusercontent.com/18468240/81919027-9182d800-95d7-11ea-858e-d4f2ea327d4f.png)

**Comment by laurent-n** [comment]
si la vignette de synthèse est sur la dernière ligne, (avec un graphe de plus par exemple c'est moins pire)

**Comment by picheral** [comment]
Ce n'est pas un problème de sécabilité du nom de projet :
![image](https://user-images.githubusercontent.com/18468240/82038282-9a40e000-96a3-11ea-9157-f9afd7df44ca.png)

**Comment by picheral** [comment]
Le problème n'est pas résolu avec des noms de projets sécables.
