### ISSUE TITLE
Mapping of taxonomy to WoRMS AphiaIDs

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#407]
Using https://www.marinespecies.org/aphia.php?p=webservice

Add a column with AphiaID into DB.

Then e.g. Copepoda X should be mapped to 'official' WoRMS.

All trees should be in full inside the DB, so creating new taxa would be unnecessary or seldom necessary.

**Comment by jiho** [comment]
The change needs to be more profound and the whole taxonomy (i.e. including the hierarchy) needs to be replaced by WoRMS ( #454 )

Closing this one since the match is part of the more global move.
