### ISSUE TITLE
Manageurs multiples de projets Ecotaxa

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#410]
Quand il y a plus de 1 manageur de projet sur Ecotaxa, celui qui apparait lors d'un request access est le premier par ordre alphabétique.
Je pense que comme on le fait pour Ecopart, il faut faire la distinction entre le data owner (celui qui devrait apparaitre au request access) et le ou les manageurs de projets (qui encadrent le travail et les analyses de ce projet).

**Comment by grololo06** [comment]
Je ne pense pas que le manager qui apparait est systématiquement le premier par ordre alphabétique, on dirait plutôt que c'est celui tout en haut de la liste de privileges. Exemple: "Zooscan point B Juday Bogorov 300 1983" fait apparaître JO qui n'est pas le premier. A quel projet penses-tu?

**Comment by picheral** [comment]
Exact

**Comment by Elineau** [comment]
oui e n'avais pas remarqué 

__________________________________________ 
Amanda Elineau 
Engineer (PIQv/CCP manager) 
Institut de la Mer - FR3761 
181 chemin du Lazaret 
06230 Villefranche sur Mer - France 
Tel : 33 +4 93 76 38 51 
__________________________________________ 



De: "grololo06" <notifications@github.com> 
À: "oceanomics" <ecotaxa_dev@noreply.github.com> 
Cc: "Elineau" <elineau@obs-vlfr.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 26 Mai 2020 09:45:07 
Objet: Re: [oceanomics/ecotaxa_dev] Manageurs multiples de projets Ecotaxa (#410) 





Je ne pense pas que le manager qui apparait est systématiquement le premier par ordre alphabétique, on dirait plutôt que c'est celui tout en haut de la liste de privileges. Exemple: "Zooscan point B Juday Bogorov 300 1983" fait apparaître JO qui n'est pas le premier. A quel projet penses-tu?

**Comment by grololo06** [comment]
Il me semble que la fonction désirée est disponible.
