### ISSUE TITLE
Difficulté de supprimer un projet 

### ISSUE THREAD

**Issue by caray-counil** [oceanomics/ecotaxa_dev#415]
Bonjour, 

Lors de la suppression d'un projet, on va choisir "delete object or project" dans le menu du projet, puis on tape DELETEALL et on coche "DELETE project after DELETEALL action." (dans mon cas Zooscan point B Juday Bogorov 300 1999). 
Problème : la page ERASE OBJECTS TOOL  charge un moment  puis une page 404 Error apparaît. 
En revenant sur le projet, on se rend compte que toutes les images ont été supprimées mais le projet existe toujours. Et il faut recommencer plusieurs fois pour que le projet disparaisse. 

J'espère avoir été clair, je suis disponible si il y a besoin de précision. 
Merci

**Comment by grololo06** [comment]
Salut Louis,
Je pense que ta suppression tourne encore, ca prend beaucoup de temps et l'utilisateur n'est pas au courant.
On a déjà #108 #324 #394 sur le sujet.

**Comment by caray-counil** [comment]
Attention, la suppression est finie, j'ai refait un autre projet Zooscan point B Juday Bogorov 300 1999 qu'il ne faut pas supprimer

**Comment by picheral** [comment]
Je partage l'analyse de Laurent. Il y a un problème d'UI à modifier pour que cela deviennent une tache.

**Comment by grololo06** [comment]
A partir de la 2.4.2, on effacera 10000 objets par seconde minimum, donc pour les petits projets comme celui-là ce sera quasi instantané.
