### ISSUE TITLE
changer la classification d'une catégorie 

### ISSUE THREAD

**Issue by caray-counil** [oceanomics/ecotaxa_dev#416]
Serait-il possible de changer la classification d'une catégorie existante sur ecotaxa ?
Je m'explique par un exemple :

Il existe la catégorie Ornithocercus, ayant la classification suivante : Ornithocercus < Dinophysaceae Oxyphysaceae < Dinophysiales < Dinophyceae < Holodinophyta < Myzozoa < Alveolata < Harosa < Eukaryota < living (id=31663)

Dans cette catégorie, il existe des sous catégories :  Ornithocercus heteroporus ;  Ornithocercus magnificus ;  Ornithocercus quadratus   etc...

Ces sous catégories ont donc comme classification (pour quadratus par exemple) Ornithocercus quadratus < Ornithocercus < Dinophysaceae Oxyphysaceae < Dinophysiales < Dinophyceae < Holodinophyta < Myzozoa < Alveolata < Harosa < Eukaryota < living (id=58201)

Cependant il existe la catégorie Ornithocercus steinii qui n'a pas la même classification que les autres Ornithocercus alors que cela devrait être le cas  Ornithocercus steinii < temporary < living (id=92505)

Ma question est donc la suivante :  est il possible de changer la classification d'une catégorie existante pour que cela soit cohérent avec les autres catégories ? sans pour autant devoir créer une nouvelle catégorie qui obligerait à une nouvelle validation ?

J'espère avoir été clair
Merci

**Comment by grololo06** [comment]
Ca me semble déjà possible pour un admin sur ecotaxoserver, il 'suffit' de changer le **parent** du taxo 'Ornithocercus steinii' de 92329 (temporary) à 31663 (living>...>Dinophysiales>Dinophysaceae Oxyphysaceae>Ornithocercus).
A voir avec @Elineau , @jiho ou @picheral car je ne suis pas admin et je ne sais pas s'il y a une antériorité d'essai.

**Comment by jiho** [comment]
Fait.

La convention avait été d'ajouter des taxa manquant en bulk dans temporary pour aller plus vite et ne pas décider d'un branchement taxonomique qui pouvait être discutable et pour lequel nous n'étions pas experts.

La taxo va être revue entièrement prochainement. J'ai donc bougé `Ornithocercus steinii` et voilà.
