### ISSUE TITLE
Bug Add preset/Add Extra

### ISSUE THREAD

**Issue by Kikouliou** [oceanomics/ecotaxa_dev#419]
J'ai voulu prendre les preset et les extra d'un projet flowcam point B et les boutons n'apparaissent pas :
![image](https://user-images.githubusercontent.com/33952113/83264963-60e29700-a1b0-11ea-8404-762a3e7c3c99.png)

**Comment by grololo06** [comment]
Lié à #409 ?

**Comment by grololo06** [comment]
Lol j'avais pas vu le code HTML dans la copie d'écran :)
