### ISSUE TITLE
Import update: recompute sun position whenever needed.

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#422]
So far the code has always been "if all data _in update data_ is present (4 fields) to recompute, then do it, otherwise leave previous value".
Users should be able to update only date _or_ time _or_ coordinates and see the new sun position.

Bare minimum: They should receive that their update data is only partially used, and be informed that by using ZooProcess to correct their data, they would ensure consistency of TSV files.

**Comment by jiho** [comment]
Solution 1 (update when one of the fields is uploaded) is preferable: one may just update some fields (especially through the API) and the recomputation should still occur.

**Comment by jiho** [comment]
The real question is "Is this sub position thing ever used?"

My guess is no... It is mostly irrelevant for sorting...

**Comment by jiho** [comment]
Ask `ecotaxa_operators` on Slack?

**Comment by picheral** [comment]
My opinion is that this that sun position may be used for ecological purposes.
It is also used for the dedicated filter
= > Do we want to remove a feature of the App ?

**Comment by jiho** [comment]
It depends if EcoTaxa is considered purely a tool for sorting images, in which case, if a function is not useful for sorting, it should be taken out (and transferring this to the pre-processing software will not be very hard).

If it is a tool for general data management then it makes sense to keep it.

**Comment by grololo06** [comment]
Fixed for 2.4.4
