### ISSUE TITLE
EcoPart : exclude CTD files with uncorrect file names when loading samples

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#424]
Ecotaxa tries to open *.cnv or other CTD files even if they do not have the correct naming convention and format.

**Comment by laurent-n** [comment]
merci de préciser le contexte voire de fournir un cas posant problème.
Pour les fichier CTD il  semble y avoir un filtre assez strict
CtdFile =  DossierUVPPath / "ctd_data_cnv"/(UvpSample.profileid+".ctd")
et pour uvp6remote
if 'CTD.txt' not in zf.namelist() :

**Comment by picheral** [comment]
C'est vrai... mais une lecture du code devrait montrer que le filtrage des fichiers n'est pas compatible à 100% avec la doc de la page explicative. Dans le cas, EcoPart a cherché à ouvrir des fichiers d'extension *.cnv !!!

**Comment by picheral** [comment]
Code vérifié. Difficile à reproduire.
