### ISSUE TITLE
Taxonomy warnings during GBIF validation

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#428]
While experimenting on #426 , the following taxa got rejected by GBIF validator (beta!) at https://www.gbif.org/fr/tools/data-validator/ using data from project https://ecotaxa.obs-vlfr.fr/prj/757

Collodaria
zoea
Harosa
Eumalacostraca
Copepoda

Status page for this attempt is at: https://www.gbif.org/fr/tools/data-validator/1580460394302
Note: The link expires 20 Jul 2020.

It looks like their rank is too high: "Subclass", "Order", "Genus", "Subkingdom", from WoRMS database.

**Comment by grololo06** [comment]
Zoea seems another case, its status is not "accepted" and taxon hierarchy is broken (family is null)
    {
      "AphiaID": 881904,
      "url": "http://www.marinespecies.org/aphia.php?p=taxdetails&id=881904",
      "scientificname": "Zoea",
      "authority": "Bosc, 1801",
      **"status": "taxon inquirendum",**
      "unacceptreason": null,
      "taxonRankID": 180,
      "rank": "Genus",
      "valid_AphiaID": 881904,
      "valid_name": "Zoea",
      "valid_authority": "Bosc, 1801",
      "parentNameUsageID": 106673,
      "kingdom": "Animalia",
      "phylum": "Arthropoda",
      "class": "Malacostraca",
      "order": "Decapoda",
      **"family": null,**
      "genus": "Zoea",
      "citation": "WoRMS (2020). Zoea Bosc, 1801. Accessed at: http://www.marinespecies.org/aphia.php?p=taxdetails&id=881904 on 2020-06-20",
      "lsid": "urn:lsid:marinespecies.org:taxname:881904",
      "isMarine": 1,
      "isBrackish": null,
      "isFreshwater": null,
      "isTerrestrial": null,
      "isExtinct": null,
      "match_type": "exact",
      "modified": "2019-08-19T14:57:19.533Z"
    }

**Comment by grololo06** [comment]
Loads of other taxa were accepted by the validator with higher rank so it's not the rank which is a problem.
e.g.:
`rank 'Class' stats {'cnt': 193, 'nms': {'Bivalvia', 'Ostracoda', 'Actinopterygii'}}`

**Comment by grololo06** [comment]
Using https://www.gbif.org/tools/species-lookup , the 4 left when removing Zoea from the list are tagged as "Not found". It looks like the taxonomy DB there is out of date or damaged.

**Comment by jiho** [comment]
To be fixed by switching the taxonomic reference to WoRMS #454

**Comment by grololo06** [comment]
Newer report: https://www.gbif.org/tools/data-validator/1602027720094 with all accepted taxa from WoRMS.

**Comment by grololo06** [comment]
Warnings are plain wrong as the EMODnet validator is OK with same data from an IPT.
