### ISSUE TITLE
The request access to project email should contain a link to the project (not just the title)

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#434]

**Comment by grololo06** [comment]
There is a "View" button in the page for requesting access to a project.

**Comment by grololo06** [comment]
![Capture d’écran de 2020-09-02 11-34-04](https://user-images.githubusercontent.com/20199778/91965062-3e609c80-ed10-11ea-84ec-471565b83c98.png)

**Comment by jiho** [comment]
Updated title to specify that I meant in a link in the text of the email.

**Comment by grololo06** [comment]
Unfortunately it's not possible to write a nice link as this kind of technique prevents use of rich HTML mail body.
See https://stackoverflow.com/questions/5620324/mailto-link-with-html-body, I guess it's for protecting users from malicious attacks.
However, the URL text for accessing the project is now in the mail body. The project manager should just copy/paste.

**Comment by jiho** [comment]
And most email clients detect URLs and turn them into links =>👌
