### ISSUE TITLE
Allow annotators to also revert to predicted for filtered classes

### ISSUE THREAD

**Issue by rkiko** [oceanomics/ecotaxa_dev#443]
@grololo06  During checking of a project and annotator might want to reset a category to predicted to allow a new prediction. Currently, that is not possible. Please allow this, JO said this should be done soon.

**Comment by grololo06** [comment]
Hi,
After discussions in the team, this function is potentially too destructive to be allowed to all annotators. The current filter could be very wide and damage thousands of objects.
We could e.g. narrow it a bit by:
- Counting the impacted objects and setting a threshold of object count.
- Allowing it only on visible objects in the page (so a maximum of 1000 objects).
But it would be much more work than the single-char modification suggested here.
A workaround is that, for the projects where it's needed, the individuals are granted by the manager the manager role, eventually just for a time window allowing such action.
