### ISSUE TITLE
Import :  se souvenir du dernier répertoire d'import pour le projet

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#445]
Cela facilitera la tache de ceux qui importent régulièrement des données dans un même projet!

**Comment by grololo06** [comment]
On garde l'info "dernier répertoire" pour chaque utilisateur (+ simple) ou pour chaque paire utilisateur/projet ?

**Comment by picheral** [comment]
Le plus sur est utilisateur/projet. L'autre cas risque de provoquer des imports malencontreux.

**Comment by jiho** [comment]
L'autre solution moins onéreuse et qui fait du sens, je pense, est par projet, indépendamment de l'utilisateur. A priori un projet va toujours avoir à peu près la même source de données, quelle que soit la personne qui importe.

**Comment by picheral** [comment]
Acceptable solution (projet)

**Comment by grololo06** [comment]
Bon bah j'ai fait la solution de luxe, par utilisateur _et_ projet, j'avais prévu de stocker les préférences pour ce couple déjà.

**Comment by jiho** [comment]
Trop rapide!

**Comment by grololo06** [comment]
Fixed in 2.4.2
