### ISSUE TITLE
Erreur d'affichage de la liste  des categories

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#447]
Projet exemple : https://ecotaxa.obs-vlfr.fr/prj/3327

J'ai classé deux objets dans like<copepoda
Je les ai ensuite déplacés dans copepoda
=> la catégorie like<copepoda reste présente comme si elle était dans un preset avec une quantité 0 alors qu'elle devrait disparaitre.

**Comment by grololo06** [comment]
Il semble que ce soit fait exprès, ce qui a du sens si par exemple l'utilisateur veut revenir sur sa classification et remettre un objet dans la catégorie désormais à 0. Il y a un bouton "Hide empty categories" si le 0 est gênant.
