### ISSUE TITLE
Too long project title makes layout of EcoPart prjedit page ugly

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#451]
See #450.
To reproduce, pick a project in EcoTaxa and set its title to the maximum allowed field length, then load the prjedit page in EcoPart, the layout will be "not nice".
The title is not needed in full, so I guess it should be truncated somehow in HTML.

**Comment by picheral** [comment]
Limiter la taille des noms de projets.... n'est pas possible à la source.
Contraindre l'affichage et tronquer.

**Comment by picheral** [comment]
Renommer aussi "Read metadata" en "Read cruise information"
