### ISSUE TITLE
Liste des dernières catégories utilisées n'est pas filtrée par le champ de saisie

### ISSUE THREAD

**Issue by Kikouliou** [oceanomics/ecotaxa_dev#463]
![image](https://user-images.githubusercontent.com/33952113/93062772-a8b0ff80-f675-11ea-9ded-d1bb0ebce3ba.png)

Exemple ci dessus : aucune catégorie proposée ne commence par "Cn" -> seul Cnidaria devrait être proposé

**Comment by grololo06** [comment]
Bug priorité 1 car entraîne des distorsions de données. Dans l'image ci-dessus, appuyer sur Entrée provoquera une **mauvaise catégorie** assignée à la vignette courante.

**Comment by grololo06** [comment]
Fixed in 2.4.2

**Comment by grololo06** [comment]
Seen on user PC:
- A single letter does not trigger filtering
- During the server request time, it's possible to type ENTER and still selection a non-filtered item

**Comment by jiho** [comment]
Cannot this be pushed to a redesign of the page? We'll need to rewrite it, possibly with a different tool no?

**Comment by grololo06** [comment]
Sure, I just re-opened to mention that it's not fully fixed.

**Comment by grololo06** [comment]
Closed with #477
