### ISSUE TITLE
Page Taxonomy filter : outil classify to + filter with child

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#465]
Quand on clique sur une catégorie avec un clique droit souris, on ouvre 2 outils classify to et filter with child.
selon la position de la catégorie cliquée la fenêtre de l'outil classify to est tronquée en haut.
Aussi si on utilise la roulette de la souris l'outil défile de haut en bas en même temps que les vignettes de droite.

![image tronquée](https://user-images.githubusercontent.com/22539675/93212452-e6d81d00-f762-11ea-986a-46f68b9a0cc5.png)

**Comment by grololo06** [comment]
Fixed in 2.4.2
