### ISSUE TITLE
Homogénéiser les noms des champs `***id`

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#47]
Le champs d'id dans la plupart des tables sont `sampleid`, `projid`, `objid`. Sauf pour la classification qui est `classif_id` dans la table `obj_head`. Il serait plus propre de le renommer en `classifid`, ou mieux `classid`.

Le champ correspondant dans la table `taxo` est `id`, ce qui complique les join. Le renommer en `classid` aussi.

Enfin, dans la table taxo, `parent_id` -> `parentid`.

**Comment by grololo06** [comment]
On ne donne pas de connexion DB à l'extérieur ça implique trop de souci de sécurité et d'infrastructure. On expose un service, dans lequel tous les renommages et arrangements sont possibles. Ceci dit, la consistance des noms est plus agréable pour maintenir le code :)
