### ISSUE TITLE
Previously chosen category can not be assigned again using autocompletion

### ISSUE THREAD

**Issue by rkiko** [oceanomics/ecotaxa_dev#477]
Following actions don't give the same result of assigning the chosen category:

1) select a few images, write "badf" (autocomplete will find badfocus>artefact), hit enter == assigns badfocus > artefact to the images

then doing exactly the same:

select a few images, write "badf" (autocomplete will find badfocus>artefact), hit enter == does not assign anything to the images (user is supposed to hit ctrl-D, but maybe the user has forgotten)

**Comment by grololo06** [comment]
Clearly, if the user can keep focusing his/her attention on the images rather than checking the state of the autocomplete box, in order to decide b/w CTRL-D and re-typing, time will be saved.

**Comment by jiho** [comment]
Can you make a video/screen capture, I am not sure I understand...

**Comment by grololo06** [comment]
Initial state:
![image](https://user-images.githubusercontent.com/20199778/94010132-ced94c80-fda5-11ea-8128-44d44dd2a88d.png)
I click on first vignette and type "detr"+ENTER
![image](https://user-images.githubusercontent.com/20199778/94010308-0d6f0700-fda6-11ea-83cc-d34137012327.png)
I click on second vignette and type (again) "detr"+ENTER
![image](https://user-images.githubusercontent.com/20199778/94010427-368f9780-fda6-11ea-8aec-a093618550b3.png)
=> Same action, different results. Bad.
Of course one might tell "it's the same just hit CTRL-D", but visually checking that it's the same might take more time than typing.

I clik on second vignette and type "detr"+ENTER

**Comment by grololo06** [comment]
Closed with #463
