### ISSUE TITLE
Homogénéiser les préfixes des champs à l'import et dans ecotaxa

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#48]
Actuellement les préfixes à l'import et dans les bases ecotaxa sont

```
img -> img
object -> obj
sample -> sample
acq -> acquis
process -> process
```

Il serait utile de les homogénéiser car cela crée des complications inutiles et peu élégantes entre le traitement des tsv à importer, les requêtes sur les tables, le traitement des tsv à l'export, etc. Je propose de changer plutôt zooprocess

- `acquis` plutôt que `acq`
- `obj` plutôt que `object`

A changer dans le code de zooprocess. A documenter dans la page d'import. A changer dans les tables sur notre serveur. A changer dans l'export des TSV depuis Ecotaxa.

**Comment by grololo06** [comment]
Le bénéfice attendu me semble faible par rapport aus coûts et aux risques. Je propose de fermer.

**Comment by picheral** [comment]
Mon opinion est indiquée plus haut. Il faudrait de plus gérer le pb des MAJ de Zooprocess pour les nombreux utilisateurs. La logique serait de mettre les bases à jour plutôt que Zooprocess puisque invisible pour les utilisateurs.

**Comment by jiho** [comment]
Le format d'import/export sera amené à changer plus drastiquement: changement de nombreux noms de champs, ajout probable d'unités, inversion des lignes de nom de champ et type de champ qui sont pénibles, etc. Donc fermons cette issue et décidons d'un nouveau format d'import/export qui satisfasse des standards internationaux et nous règlerons tous les pbs en une fois.

Et oui il faudra tolérer les anciens fichiers pendant un moment ;-)
