### ISSUE TITLE
Possibilité de rechercher un projet par mot clé lors d'un merge

### ISSUE THREAD

**Issue by Kikouliou** [oceanomics/ecotaxa_dev#491]
Lorsque l'on veut merger un projet à un autre, il n'existe pas de possibilité de rechercher un projet par mot clé ou autre filtrage 

![image](https://user-images.githubusercontent.com/33952113/94704006-bafe8f00-033f-11eb-8852-809f50be573f.png)

Pour l'instant, j'utilise Ctrl+F

**Comment by grololo06** [comment]
Hello,
Regarde STP si #182 convient à ton idée, et merci d'entrer la prochaine issue en Anglais ;-)

**Comment by Kikouliou** [comment]
Bonjour Grololo06
Je suis désolée mais je ne comprends pas l'issue 182... Trop de termes techniques :-/

**Comment by grololo06** [comment]
Oki, je t'invite à suivre #182 (il y a un bouton "Subscribe" accessible pour toi), et à ré-ouvrir la présente issue si, une fois qu'elle est résolue, il n'y a pas ce qu'il te faut. Tu peux aussi la 'liker'!
