### ISSUE TITLE
'Erase objects tool' can remove objects outside of current project

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#501]
After its move to back-end, the function is using the API primitive which deletes any object, provided that current user has proper rights to do so.
It's not in the spirit of the page, so, outside of current project, the manually entered object IDs should not be deleted.

**Comment by picheral** [comment]
The DELETE page should be modified. We must have a specific page to delete the entire project accessible from the PROJECT menu and a different page to remove selected objects using the FILTER menu. The possibility to remove objects from their Ids entered manuallt should be moved elsewhere or suppressed.

**Comment by grololo06** [comment]
Yep, we have also #108 for other delete requirements.

**Comment by jiho** [comment]
That said, from the API, delete should be able to delete any object set that the user has rights on.

So I think the API should stay as it is and the UI should be changed to allow to delete all objects of a project or only objects based on a filter (which would necessarily be inside of a single project --or collection in the future-- for each call).

**Comment by grololo06** [comment]
Minimal fix just to prevent accidents until #108
