### ISSUE TITLE
sampleid is bigint in ecotaxa integer in ecopart

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#503]
```
select column_name,data_type 
from information_schema.columns 
where table_name = 'part_samples';

select column_name,data_type 
from information_schema.columns 
where table_name = 'samples';
```

By the way, this shows that there are many copies of the same table in `information_schema`.

**Comment by grololo06** [comment]
The multiple copies were due to imported DBs, so I guess it's not the case anymore now.

**Comment by grololo06** [comment]
Worse than that, the foreign key to `samples` (in EcoTaxa) in `obj_head` is a plain integer.
Same problem for `process` and `acquisitions`.
It looks like SQLAlchemy does a loose type checking when declaring a FK.
