### ISSUE TITLE
Add project-level metadata fields necessary for EMODnet export

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#504]
Needed for #426 

- [ ] Dataset title -> project title?
- [ ] Contact person(s) (will be data owner) Cf #81 
- [x] Data creator -> all annotators (including historical ones) + others persons to be credited (role to be created)
- [x] Licence Cf #244 
- [ ] Abstract/description (with guidance regarding the content to be copied from EMODnet's requirements)
- [x] Geographical coverage -> to be computed from samples
- [x] Temporal coverage -> to be computed from samples
- [x] Taxonomic coverage -> to be computed from objets
- [x] Functional groups: plankton
- [ ] Keywords: plankton, imaging, ecotaxa + instrument
- [ ] Instrument Cf #264 

To be added to db and Project settings page. Then email to all project managers.

**Comment by grololo06** [comment]
During discussion on the 27th of Oct it's been decided to have collection-level data instead -> #519
