### ISSUE TITLE
Filtres custom n'incluent pas toutes les possibilités

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#51]
Dans les filtres numériques, il n'y a que les champs des objets. Cela est peut-être normal car peut-être que les champs libres des samples, acquis, etc. sont tous "texte".

Dans le filtre texte il n'y a que des champs de sample, process, acquis. Or je crois qu'il y avait des champs texte pour les objets aussi non?

Use case: je voulais chercher sur le original object id et c'est actuellement impossible.

**Comment by grololo06** [comment]
#446, les champs texte libre sur objet ne marchaient pas. Ce sera OK en 2.4.2. Attention, orig_id n'est pas un texte libre, s'il faut pouvoir chercher dessus merci d'ouvrir une nouvelle issue spécifique.
