### ISSUE TITLE
Edit project settings page is compressed to the left

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#524]
This is linked with the addition of the license information.

Solution: Format the license dropdown the same was as the rest of the choices; place it underneath "Visible for all visitors"

![Screenshot 2020-11-06 at 14 46 42](https://user-images.githubusercontent.com/18445/98373112-0ee74c80-203f-11eb-9c2c-5944410cb8ff.png)

**Comment by grololo06** [comment]
Oops I forgot to copy the fixed length of the TD element...
