### ISSUE TITLE
Encodage des données manquantes dans l'export .tsv

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#53]
Les données manquantes dans les champs numériques sont écrites comme `""`, i.e. une chaine de caractères vide. Elles devraient simplement correspondre à deux tabulations successives i.e. rien.

Dans les format csv ou tsv les champs "texte" doivent être encadrés par des guillemets, les champs "numérique" non, même s'ils sont vides.

**Comment by grololo06** [comment]
Ca m'a l'air OK d'un test fait ce matin.
