### ISSUE TITLE
Merging error from one project to another project

### ISSUE THREAD

**Issue by kimdonggyun** [oceanomics/ecotaxa_dev#532]
<img width="823" alt="Screenshot 2020-11-12 at 13 53 02" src="https://user-images.githubusercontent.com/19298738/99044490-1ef7b280-2590-11eb-98ef-bffe9338baa0.png">
<img width="1019" alt="Screenshot 2020-11-12 at 13 53 23" src="https://user-images.githubusercontent.com/19298738/99044524-2d45ce80-2590-11eb-8215-f615cc46ee52.png">

Merging issue occurred while the function 'Merge another project in this project'.
This issue happened on the projects uploaded from LOKI projects.

**Comment by grololo06** [comment]
Hello, it's fixed now, the page does not return any error.
