### ISSUE TITLE
Object details sometimes do not show

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#534]
Steps to reproduce:
1. Go to https://ecotaxa.obs-vlfr.fr/prj/3364?taxo=25990&taxochild=N&ipp=100&zoom=100&sortby=n57&magenabled=0&popupenabled=0&statusfilter=&samples=&instrum=&sortorder=desc&dispfield=+dispfield_n57&projid=3364&pageoffset=0 
2. Click on the eye icon for the first object: the modal stays stuck in "Loading"
3. Click on the eye icon for the second object: modal appears

<img width="730" alt="Screenshot 2020-11-14 at 00 06 21" src="https://user-images.githubusercontent.com/18445/99129277-63756380-260d-11eb-9949-3600d04cf444.png">

**Comment by grololo06** [comment]
Is due to #389 , we now don't show partial objects details. The first object was completed with a dummy "process" objects, the second wasn't.

**Comment by jiho** [comment]
Does the import process create the dummy sample/acq/process when they are missing in the input file?

**Comment by grololo06** [comment]
Not yet, that's why #389 is still opened. So far there is only a SQL script for fixing data on DB.

**Comment by grololo06** [comment]
I ran the script, so it's OK now. I suggest the TSV generator program to add the column process_id with some data, waiting for #389 to be fixed.
