### ISSUE TITLE
Progress bar on export page is wrong

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#537]
It shows 1% for a while and then jumps to 100% when the export is done.

Change it to an infinite loader animation, like https://www.w3schools.com/howto/howto_css_loader.asp

**Comment by grololo06** [comment]
Good news, it's a plain bug, as the query can be very fast, but the progress bar is not updated during TSV generation:
`2020-11-17 13:47:57,918 - root - INFO - Execute SPCommon for Txt Export
2020-11-17 13:47:57,926 - root - INFO - Input Param = {'steperrors': [], 'ProjectId': '398', 'what': 'BAK', 'Details': None, 'OutFile': None, 'filtres': {}, 'samplelist': '', 'commentsdata': '', 'objectdata': '1', 'sampledata': '1', 'processdata': '1', 'acqdata': '1', 'histodata': '', 'splitcsvby': '', 'usecomasepa': '', 'sumsubtotal': 'W', 'internalids': '', 'typeline': '', 'putfileonftparea': '', 'use_internal_image_name': '', 'exportimagesbak': '', 'exportimagesdoi': ''}
2020-11-17 13:47:57,940 - root - INFO - Execute SQL : select o.orig_id as object_id, o.latitude as object_lat, o.longitude as object_lon,
                         to_char(objdate,'YYYYMMDD') as object_date,
                         to_char(objtime,'HH24MISS') as object_time,
                         object_link, depth_min as object_depth_min, depth_max as object_depth_max,
                         case o.classif_qual 
                            when 'V' then 'validated' 
                            when 'P' then 'predicted' 
                            when 'D' then 'dubious' 
                            else o.classif_qual 
                         end object_annotation_status,                
                         uo1.name object_annotation_person_name, uo1.email object_annotation_person_email,
                         to_char(o.classif_when,'YYYYMMDD') object_annotation_date,
                         to_char(o.classif_when,'HH24MISS') object_annotation_time,                
                         to1.display_name as object_annotation_category 
                    ,to1.id as object_annotation_category_id
,o.n01 as "object_lat_end" ,o.n02 as "object_lon_end" ,o.n03 as "object_area" ,o.n04 as "object_mean" ,o.n05 as "object_stddev" ,o.n06 as "object_mode" ,o.n07 as "object_min" ,o.n08 as "object_max" ,o.n09 as "object_x" ,o.n10 as "object_y" ,o.n11 as "object_xm" ,o.n12 as "object_ym" ,o.n13 as "object_perim." ,o.n14 as "object_bx" ,o.n15 as "object_by" ,o.n16 as "object_width" ,o.n17 as "object_height" ,o.n18 as "object_major" ,o.n19 as "object_minor" ,o.n20 as "object_angle" ,o.n21 as "object_circ." ,o.n22 as "object_feret" ,o.n23 as "object_intden" ,o.n24 as "object_median" ,o.n25 as "object_skew" ,o.n26 as "object_kurt" ,o.n27 as "object__area" ,o.n28 as "object_xstart" ,o.n29 as "object_ystart" ,o.n30 as "object_area_exc" ,o.n31 as "object_fractal" ,o.n32 as "object_skelarea" ,o.n33 as "object_slope" ,o.n34 as "object_histcum1" ,o.n35 as "object_histcum2" ,o.n36 as "object_histcum3" ,o.n37 as "object_xmg5" ,o.n38 as "object_ymg5" ,o.n39 as "object_nb1" ,o.n40 as "object_nb2" ,o.n41 as "object_nb3" ,o.n42 as "object_compentropy" ,o.n43 as "object_compmean" ,o.n44 as "object_compslope" ,o.n45 as "object_compm1" ,o.n46 as "object_compm2" ,o.n47 as "object_compm3" ,o.n48 as "object_symetrieh" ,o.n49 as "object_symetriev" ,o.n50 as "object_symetriehc" ,o.n51 as "object_symetrievc" ,o.n52 as "object_convperim" ,o.n53 as "object_convarea" ,o.n54 as "object_fcons" ,o.n55 as "object_thickr" ,o.n56 as "object_tag" ,o.n57 as "object_esd" ,o.n58 as "object_elongation" ,o.n59 as "object_range" ,o.n60 as "object_meanpos" ,o.n61 as "object_centroids" ,o.n62 as "object_cv" ,o.n63 as "object_sr" ,o.n64 as "object_perimareaexc" ,o.n65 as "object_feretareaexc" ,o.n66 as "object_perimferet" ,o.n67 as "object_perimmajor" ,o.n68 as "object_circex" ,o.n69 as "object_cdexc" ,o.t01 as "object_annotation_person_me" 
,s.orig_id sample_id,s.dataportal_descriptor as sample_dataportal_descriptor ,s.t01 as "sample_scan_operator" ,s.t02 as "sample_ship" ,s.t03 as "sample_program" ,s.t04 as "sample_stationid" ,s.t05 as "sample_bottomdepth" ,s.t06 as "sample_ctdrosettefilename" ,s.t07 as "sample_other_ref" ,s.t08 as "sample_tow_nb" ,s.t09 as "sample_tow_type" ,s.t10 as "sample_net_type" ,s.t11 as "sample_net_mesh" ,s.t12 as "sample_net_surf" ,s.t13 as "sample_zmax" ,s.t14 as "sample_zmin" ,s.t15 as "sample_tot_vol" ,s.t16 as "sample_comment" ,s.t17 as "sample_tot_vol_qc" ,s.t18 as "sample_depth_qc" ,s.t19 as "sample_sample_qc" ,s.t20 as "sample_barcode" ,s.t21 as "sample_duration" ,s.t22 as "sample_ship_speed" ,s.t23 as "sample_cable_length" ,s.t24 as "sample_cable_angle" ,s.t25 as "sample_cable_speed" ,s.t26 as "sample_nb_jar" ,s.t27 as "sample_open" 
,p.orig_id process_id,p.t01 as "process_date" ,p.t02 as "process_time" ,p.t03 as "process_img_software_version" ,p.t04 as "process_img_resolution" ,p.t05 as "process_img_od_grey" ,p.t06 as "process_img_od_std" ,p.t07 as "process_img_background_img" ,p.t08 as "process_particle_version" ,p.t09 as "process_particle_threshold" ,p.t10 as "process_particle_pixel_size_mm" ,p.t11 as "process_particle_min_size_mm" ,p.t12 as "process_particle_max_size_mm" ,p.t13 as "process_particle_sep_mask" ,p.t14 as "process_particle_bw_ratio" ,p.t15 as "process_software" 
,a.orig_id acq_id,a.instrument as acq_instrument,a.t01 as "acq_min_mesh" ,a.t02 as "acq_max_mesh" ,a.t03 as "acq_sub_part" ,a.t04 as "acq_sub_method" ,a.t05 as "acq_hardware" ,a.t06 as "acq_software" ,a.t07 as "acq_author" ,a.t08 as "acq_imgtype" ,a.t09 as "acq_scan_date" ,a.t10 as "acq_scan_time" ,a.t11 as "acq_quality" ,a.t12 as "acq_bitpixel" ,a.t13 as "acq_greyfrom" ,a.t14 as "acq_scan_resolution" ,a.t15 as "acq_rotation" ,a.t16 as "acq_miror" ,a.t17 as "acq_xsize" ,a.t18 as "acq_ysize" ,a.t19 as "acq_xoffset" ,a.t20 as "acq_yoffset" ,a.t21 as "acq_lut_color_balance" ,a.t22 as "acq_lut_filter" ,a.t23 as "acq_lut_min" ,a.t24 as "acq_lut_max" ,a.t25 as "acq_lut_odrange" ,a.t26 as "acq_lut_ratio" ,a.t27 as "acq_lut_16b_median"   from objects o
                left join taxonomy to1 on o.classif_id = to1.id
                left join taxonomy to1p on to1.parent_id = to1p.id
                left join users uo1 on o.classif_who = uo1.id
                left join taxonomy to2 on o.classif_auto_id = to2.id
                left join samples s on o.sampleid = s.sampleid  left join process p on o.processid=p.processid  left join acquisitions a on o.acquisid = a.acquisid   where o.projid=%(projid)s  order by s.orig_id, o.objid 
2020-11-17 13:47:57,940 - root - INFO - Params : {'projid': 398}
2020-11-17 13:53:20,304 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:20,667 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:21,039 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:21,415 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:21,766 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:22,113 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:22,495 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:22,759 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:23,027 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:23,360 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:23,684 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv
2020-11-17 13:53:24,110 - root - INFO - Creating file /home/ecotaxa/ecotaxa/temptask/task037705/temp.tsv`

**Comment by grololo06** [comment]
Solved in 2.5.0 for what can be (no progress can be simply displayed during a very long query)
