### ISSUE TITLE
URGENT : Pb NaN qui empêchent la prédiction

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#59]
Nous entrions jusqu'ici des champs object_lat_end et object_lon_end en [f] avec des codes valeurs manquantes 9999 ou -9999. 
Cela ne posait aucun problème de prédiction. Nous remplaçons maintenant ces codes par le code NaN et même lorsque nous décochons ces variables dans l'écran de prédiction, cela empêche toute prédiction : Unhandled SubProcess Exception : (, ValueError("Input contains NaN, infinity or a value too large for dtype('float32').",), )
Ayant de multiples samples, projets déjà importés ainsi que des versions de Zooprocess dans la nature qui créent ces NaN, la seule solution est qu'ecotaxa soit capable de gérer cela !!!

**Comment by grololo06** [comment]
'na' et 'nan' (quelle que soit la casse) sont filtrés vers '' i.e. rien dans les imports EcoTaxa.
