### ISSUE TITLE
Traiter les -infinity à l'import et au re-import

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#61]
Le fait de traiter aussi au re-import permet de solutionner le problème par et pour chaque utilisateur

**Comment by picheral** [comment]
Certains TSV issus de Zooprocess contenaient des -inf. Ceci a été corrigé dans Zooprocess mais nous ne pouvons écarter le risque que certains utilisateurs utilisent des versions obsolètes. Remplacer le -inf par le code valeur manquante.

**Comment by picheral** [comment]
lié à #59

**Comment by grololo06** [comment]
Pas difficile, mais il faudrait un fichier exemple.

**Comment by picheral** [comment]
Prendre un TSV et mettre quelques -inf
