### ISSUE TITLE
Probleme d'affichage si resultat filtre trop grand

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#62]
Avant filtre 👍 
![image](https://cloud.githubusercontent.com/assets/18468240/24512158/192aee02-156e-11e7-9cce-9bac92e1eeb9.png)
Après filtre 👍 
![image](https://cloud.githubusercontent.com/assets/18468240/24512197/343f139e-156e-11e7-841f-02b9dd6bdc1a.png)
On a perdu les outils !!!!

**Comment by grololo06** [comment]
Je n'arrive pas à le reproduire, je le ferme par optimisme :)
