### ISSUE TITLE
Pas de sélection d'année dans le filtre date

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#64]
Défaut de scroll "année", voir projet 346 qui s'étend sur des décennies

**Comment by grololo06** [comment]
![Capture d’écran de 2020-09-02 10-54-19](https://user-images.githubusercontent.com/20199778/91960870-b7f58c00-ed0a-11ea-9d57-141d069798fd.png)
Il a dû apparaître depuis que cette issue a été créée.
