### ISSUE TITLE
Import database (à partir d'un projet)

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#68]
Le texte indique qu'on importe une database dans un projet vide préalablement créé.... alors qu'il n'en n'est rien. Les écrans suivants proposent d'aller choisir parmi tous les projets comme si on était admin de l'appli !

**Comment by grololo06** [comment]
Je lis "To import from another Ecotaxa instance in an empty project.", en dessous un gros bouton bleu "Start import a project exported from another instance". Est-ce de lui qu'il s'agit? Je ne vois pas de choix de projet dans la page suivante.

**Comment by picheral** [comment]
EXactement... Le comportement est aberrant. On doit être DANS un projet pour accéder à ce gros bouton bleu. Si on l'utilise, on accède alors à la possibilité d'importer dans un NOUVEAU projet et pas dans celui duquel on est parti ! On pourra regarder un écran ensemble pour démo.

**Comment by picheral** [comment]
Petite explication devant l'écran import aiderait à expliquer...

**Comment by grololo06** [comment]
L'entrée pour importer une DB est déjà dans la menu spécifique admin donc je l'enlève de la page import utilisateur.
