### ISSUE TITLE
Améliorer sélection des users dans Edit project settings

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#72]
Actuellement c'est un select avec les utilisateurs listés a en "Prénom Nom". Ce n'est pas idéal car on ne connait pas forcément les prénoms.

L'idéal serait de reprendre (au moins l'idée de) l'interface dynamique d'ajout d'un privilège quand on crée un projet dans l'interface d'admin.

**Comment by picheral** [comment]
Filtre sera amélioré.
Prévu d'améliorer la saisie dans  #189
