### ISSUE TITLE
Automatic classification fails when values of variables are nan/Inf

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#8]
Example: variable `meanpos` in project http://ecotaxa.obs-vlfr.fr/prj/187
Some values are `nan` others are `=-infinity` in the import file (NB: it is probably a bug in zooprocess but still, ecotaxa should be able to handle it).

Ideally, those values should be considered as missing. Missing values are handled by the prediction process (I think).

**Comment by grololo06** [comment]
It seems correctly managed in a code commit of  nov 2017, so I close.
