### ISSUE TITLE
Création de projet "parent/enfant" remplaçant le merge (meta-project)

### ISSUE THREAD

**Issue by Elineau** [oceanomics/ecotaxa_dev#82]
--> Pouvoir regrouper des projets différents dans un unique projet sans perdre l'unicité des projets.
ex: 
> Je créer le dossier point B wp2 où je retrouve dedans la liste de chacun des projets du wp2. Donc si je clique sur le dossier parent j'ai tous les projets merger mais si j'ouvre la petite flèche à gauche du dossier parent j'ai accès à chaque projet du ptB individualisé. Je pourrais alors valider en mode "merge" dans le dossier "parent" ce qui appliquerait la même modification dans le sous projet "enfant" et inversement bien sur si je décide de valider en mode individualisé. 

Cela ne peut marcher que si le mapping de tous les projets est le même.
Je pensais également à une solution similaire (i.e. des "meta-projets") pour résoudre un des "pbs" avec l'UVP (plusieurs projets zooprocess et particules sont désirables mais on voudrait qu'ils correspondent à un seul projet plancton) et l'affichage d'autres projets (e.g. le point B, qui devrait vraiment apparaitre comme un seul projet) tout en gardant le mapping 1-1 avec zooprocess.

**Comment by jiho** [comment]
Superseded by #519
