### ISSUE TITLE
EcoPart: Wrong project manager in stats page

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#86]
Le Project Manager qui s'affiche dans la page STATS n'est pas celui qui a réellement les droits dans le Project management.

**Comment by grololo06** [comment]
Sur e.g. https://ecotaxa.obs-vlfr.fr/part/prjedit/56
Marcel Babin est Project Owner (il n'y a pas de champ Manager).
Il apparait également sur la page stats.
![Capture d’écran de 2020-04-28 08-47-04](https://user-images.githubusercontent.com/20199778/80455926-f0d0bf00-892c-11ea-8107-761324381573.png)
On peut fermer?

**Comment by picheral** [comment]
Résolu
