### ISSUE TITLE
Bug dans le mapping automatique des taxons à l'import

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#87]
There are several categories for which no unique identifier is used for export and import.

E.g. I have exported a category 'like (Copepoda)'. Reimporting randomly splits this category into 'like (Copepoda)' and 'like (Laomediidae)'
The same happens with not-living > detritus > fluffy > light (id=85135)  of which many get into  not-living > geometric > disc > light (id=85088)
and not-living > detritus > fluffy > dark (id=85134) of which many get into not-living > geometric > disc > dark (id=85087)

It seems to me that the export / import is not well restricted. I believe that this is due to the fact that 'like', 'light' or 'dark' is the 'object_annotation_category'. As these are not unique, there can not be a proper reimport unless also the "object_annotation_parent_category" is used during import. I would actually recommend to also output the id (e.g. 85135) in the export (which I guess is unique?) and to only rely on that in the import or to use the object_annotation_hierarchy ...

Or am I doing something wrong? If yes, it would be great if you could let me know how to reimport properly.

**Comment by jiho** [comment]
Toute catégorie dont le nom est non-unique ("dead", "like", etc.) est remappé à un des synonymes sans savoir lequel et sans émettre de warning. Il faut utiliser un système de désambiguation. cf #172

**Comment by picheral** [comment]
Probablement réglé... Difficile à reproduire !

**Comment by jiho** [comment]
Pb pas complètement réglé. Test en fichier joint ([import de categories ambigues.zip](https://github.com/oceanomics/ecotaxa_dev/files/2172283/import.de.categories.ambigues.zip)) et résultat ici http://ecotaxa.obs-vlfr.fr/prj/1100

Tous les objets sont nommés "part"
- deux objets validés sont nommés "part (parent)" -> ils sont bien classés
- deux objets predicted sont nommés "part" et la colonne `object_annotation_parent_category` est vide -> ils sont mal classés, comme "part (Mysida)", sans warning à l'import
- deux objets dubious sont nommés "part" et la colonne `object_annotation_parent_category` contient le nom de leur parent -> idem

Il faudrait:
- éventuellement utiliser la colonne `object_annotation_parent_category` quand elle existe, là elle est considérée comme une feature de l'objet.
- toujours demander un mapping explicite par l'utilisateur quand le nom de la catégorie est ambigu: "part", "dead", "like", etc. = tous ceux qui sont dupliqués dans la taxo. Une possibilité d'implémentation est de faire le match sur le `display name` (cf #172) ce qui résulterait donc en aucun match pour les cas ambigus (car ils sont écrits "nom (nom du parent)") et forcerait à un remapping à l'entrée.

**Comment by picheral** [comment]
Ne devrait plus arriver avec les nouveaux exports. Cependant traiter en demandant que faire des "part" seuls ? Pas de traitement automatique.

**Comment by picheral** [comment]
Afin d'éviter de passer des heures à coder un mapping pour des cas qui ne se rencontreront à l'avenir que sur des fichiers prédits en externe et mal construits, on pourrait "seulement" implémenter des tests à l'import et afficher un warning adapté.
La page "How to import..." est précise et indique bien que le parent doit être entre "( )".

**Comment by grololo06** [comment]
Me semble correctement implémenté en 2.2 et en 2.3.
