### ISSUE TITLE
Ecopart?: Import particle "permission denied"

### ISSUE THREAD

**Issue by picheral** [oceanomics/ecotaxa_dev#88]
Problème de permission qui nous oblige à supprimer les PNG avant de ré-importer. On a un "permission denied" pour écraser les fichiers issus d'un import préalable.

**Comment by grololo06** [comment]
Toujours d'actualité?

**Comment by grololo06** [comment]
A ré-essayer STP.

**Comment by picheral** [comment]
Problème résolu.
